// Sistema de etiquetado de ferias por actividad.
// families: cada familia = un 'sector' de fairsData, con su color (código de colores).
// tags: etiqueta -> { family, label } (label en los 11 idiomas).
// fairActivities: slug de feria -> [etiquetas] (multivalor). Fuente de verdad del etiquetado.
// label: nombre de la familia en los 11 idiomas (cabeceras de subfamilia en el
// índice /actividad y en el asesor Pat). sector = nombre ES (compat interna).
export const tagFamilies = {
  agroalimentario: { sector: "Agroalimentario y Naturaleza", color: '#3A9D4E', label: { es: "Agroalimentario y Naturaleza", pt: "Agroalimentar e Natureza", en: "Agrifood & Nature", de: "Agrar & Natur", fr: "Agroalimentaire et nature", it: "Agroalimentare e natura", nl: "Agrovoeding & natuur", zh: "农业食品与自然", hi: "कृषि-खाद्य एवं प्रकृति", ko: "농식품 및 자연", ja: "農産物・自然" } },
  industria: { sector: "Industria y Logística", color: '#5B6B7A', label: { es: "Industria y Logística", pt: "Indústria e Logística", en: "Industry & Logistics", de: "Industrie & Logistik", fr: "Industrie et logistique", it: "Industria e logistica", nl: "Industrie & logistiek", zh: "工业与物流", hi: "उद्योग एवं लॉजिस्टिक्स", ko: "산업 및 물류", ja: "産業・物流" } },
  salud: { sector: "Salud y Medicina", color: '#E05A5A', label: { es: "Salud y Medicina", pt: "Saúde e Medicina", en: "Health & Medicine", de: "Gesundheit & Medizin", fr: "Santé et médecine", it: "Salute e medicina", nl: "Gezondheid & geneeskunde", zh: "健康与医学", hi: "स्वास्थ्य एवं चिकित्सा", ko: "건강 및 의학", ja: "健康・医療" } },
  tecnologia: { sector: "Tecnología e Innovación", color: '#2F7FD1', label: { es: "Tecnología e Innovación", pt: "Tecnologia e Inovação", en: "Technology & Innovation", de: "Technologie & Innovation", fr: "Technologie et innovation", it: "Tecnologia e innovazione", nl: "Technologie & innovatie", zh: "科技与创新", hi: "तकनीक एवं नवाचार", ko: "기술 및 혁신", ja: "テクノロジー・イノベーション" } },
  comercio: { sector: "Comercio y Packaging", color: '#E8902A', label: { es: "Comercio y Packaging", pt: "Comércio e Packaging", en: "Retail & Packaging", de: "Handel & Verpackung", fr: "Commerce et packaging", it: "Commercio e packaging", nl: "Handel & verpakking", zh: "商贸与包装", hi: "व्यापार एवं पैकेजिंग", ko: "유통 및 패키징", ja: "商業・パッケージ" } },
  construccion: { sector: "Construcción e Infraestructuras", color: '#A8763E', label: { es: "Construcción e Infraestructuras", pt: "Construção e Infraestruturas", en: "Construction & Infrastructure", de: "Bau & Infrastruktur", fr: "Construction et infrastructures", it: "Costruzione e infrastrutture", nl: "Bouw & infrastructuur", zh: "建筑与基础设施", hi: "निर्माण एवं अवसंरचना", ko: "건설 및 인프라", ja: "建設・インフラ" } },
  turismo: { sector: "Turismo y Hostelería", color: '#1AA7A0', label: { es: "Turismo y Hostelería", pt: "Turismo e Hotelaria", en: "Tourism & Hospitality", de: "Tourismus & Gastgewerbe", fr: "Tourisme et hôtellerie", it: "Turismo e ospitalità", nl: "Toerisme & horeca", zh: "旅游与酒店", hi: "पर्यटन एवं आतिथ्य", ko: "관광 및 호스피탈리티", ja: "観光・ホスピタリティ" } },
  transporte: { sector: "Aeronáutica y Transporte", color: '#34508C', label: { es: "Aeronáutica y Transporte", pt: "Aeronáutica e Transporte", en: "Aerospace & Transport", de: "Luftfahrt & Transport", fr: "Aéronautique et transport", it: "Aeronautica e trasporti", nl: "Luchtvaart & transport", zh: "航空与交通", hi: "विमानन एवं परिवहन", ko: "항공 및 운송", ja: "航空・輸送" } },
  enologia: { sector: "Enología y Vinos", color: '#7A2E46', label: { es: "Enología y Vinos", pt: "Enologia e Vinhos", en: "Wine & Oenology", de: "Wein & Önologie", fr: "Œnologie et vins", it: "Enologia e vini", nl: "Wijn & oenologie", zh: "葡萄酒与酿酒", hi: "वाइन एवं एनोलॉजी", ko: "와인 및 양조", ja: "ワイン・醸造" } },
  ocio: { sector: "Arte y Ocio", color: '#8E5BB5', label: { es: "Arte y Ocio", pt: "Arte e Lazer", en: "Art & Leisure", de: "Kunst & Freizeit", fr: "Art et loisirs", it: "Arte e tempo libero", nl: "Kunst & vrije tijd", zh: "艺术与休闲", hi: "कला एवं मनोरंजन", ko: "예술 및 여가", ja: "アート・レジャー" } },
  belleza: { sector: "Belleza y Estética", color: '#D6589E', label: { es: "Belleza y Estética", pt: "Beleza e Estética", en: "Beauty & Aesthetics", de: "Schönheit & Ästhetik", fr: "Beauté et esthétique", it: "Bellezza ed estetica", nl: "Schoonheid & esthetiek", zh: "美容与美学", hi: "सौंदर्य एवं एस्थेटिक्स", ko: "뷰티 및 에스테틱", ja: "ビューティー・エステ" } },
  multi: { sector: "Multisectorial y Profesional", color: '#6F757D', label: { es: "Multisectorial y Profesional", pt: "Multissetorial e Profissional", en: "Multi-sector & Professional", de: "Multisektoral & Professionell", fr: "Multisectoriel et professionnel", it: "Multisettoriale e professionale", nl: "Multisectoraal & professioneel", zh: "综合与专业", hi: "बहु-क्षेत्रीय एवं पेशेवर", ko: "다분야 및 전문", ja: "総合・専門" } }
};

export const fairTags = {
  "alimentacion": { family: "agroalimentario", label: { es: "Alimentación", pt: "Alimentação", en: "Food & beverage", de: "Lebensmittel", fr: "Alimentation", it: "Alimentare", nl: "Voeding", zh: "食品", hi: "खाद्य एवं पेय पदार्थ", ko: "식품", ja: "食品" } },
  "ganaderia": { family: "agroalimentario", label: { es: "Ganadería", pt: "Pecuária", en: "Livestock", de: "Viehwirtschaft", fr: "Élevage", it: "Zootecnia", nl: "Veeteelt", zh: "畜牧业", hi: "पशुपालन", ko: "축산", ja: "畜産" } },
  "agricultura-maquinaria": { family: "agroalimentario", label: { es: "Agricultura y maquinaria agrícola", pt: "Agricultura e maquinaria agrícola", en: "Agriculture & farm machinery", de: "Landwirtschaft und Landmaschinen", fr: "Agriculture et machinisme agricole", it: "Agricoltura e macchine agricole", nl: "Landbouw en landbouwmachines", zh: "农业与农业机械", hi: "कृषि एवं कृषि मशीनरी", ko: "농업 및 농기계", ja: "農業・農業機械" } },
  "ecologico": { family: "agroalimentario", label: { es: "Ecológico y sostenible", pt: "Ecológico e sustentável", en: "Organic & sustainable", de: "Bio und Nachhaltigkeit", fr: "Bio et développement durable", it: "Biologico e sostenibile", nl: "Biologisch en duurzaam", zh: "有机与可持续", hi: "जैविक एवं टिकाऊ", ko: "친환경 및 지속가능", ja: "オーガニック・サステナブル" } },
  "pesca-mar": { family: "agroalimentario", label: { es: "Pesca y mar", pt: "Pesca e mar", en: "Fishing & seafood", de: "Fischerei und Meer", fr: "Pêche et produits de la mer", it: "Pesca e prodotti del mare", nl: "Visserij en zee", zh: "渔业与海洋", hi: "मत्स्य पालन एवं समुद्री उत्पाद", ko: "수산 및 해양", ja: "水産・海洋" } },
  "maquinaria-industrial": { family: "industria", label: { es: "Maquinaria industrial", pt: "Maquinaria industrial", en: "Industrial machinery", de: "Industriemaschinen", fr: "Machines industrielles", it: "Macchine industriali", nl: "Industriële machines", zh: "工业机械", hi: "औद्योगिक मशीनरी", ko: "산업 기계", ja: "産業機械" } },
  "metal-subcontratacion": { family: "industria", label: { es: "Metal y subcontratación", pt: "Metalomecânica e subcontratação", en: "Metalworking & subcontracting", de: "Metall und Zulieferindustrie", fr: "Métal et sous-traitance", it: "Metallo e subfornitura", nl: "Metaal en toelevering", zh: "金属与工业外包", hi: "धातु एवं उप-अनुबंध", ko: "금속 및 임가공", ja: "金属・受託製造" } },
  "limpieza-higiene": { family: "industria", label: { es: "Limpieza e higiene profesional", pt: "Limpeza e higiene profissional", en: "Professional cleaning & hygiene", de: "Reinigung und professionelle Hygiene", fr: "Nettoyage et hygiène professionnelle", it: "Pulizia e igiene professionale", nl: "Schoonmaak en professionele hygiëne", zh: "清洁与专业卫生", hi: "सफ़ाई एवं पेशेवर स्वच्छता", ko: "청소 및 전문 위생", ja: "清掃・業務用衛生" } },
  "logistica": { family: "industria", label: { es: "Logística", pt: "Logística", en: "Logistics", de: "Logistik", fr: "Logistique", it: "Logistica", nl: "Logistiek", zh: "物流", hi: "लॉजिस्टिक्स", ko: "물류", ja: "物流" } },
  "energia": { family: "industria", label: { es: "Energía", pt: "Energia", en: "Energy", de: "Energie", fr: "Énergie", it: "Energia", nl: "Energie", zh: "能源", hi: "ऊर्जा", ko: "에너지", ja: "エネルギー" } },
  "dental": { family: "salud", label: { es: "Dental y ortodoncia", pt: "Dentária e ortodontia", en: "Dental & orthodontics", de: "Dental und Kieferorthopädie", fr: "Dentaire et orthodontie", it: "Dentale e ortodonzia", nl: "Tandheelkunde en orthodontie", zh: "牙科与正畸", hi: "डेंटल एवं ऑर्थोडॉन्टिक्स", ko: "치과 및 교정", ja: "歯科・矯正歯科" } },
  "optica-oftalmologia": { family: "salud", label: { es: "Óptica y oftalmología", pt: "Ótica e oftalmologia", en: "Optics & ophthalmology", de: "Optik und Augenheilkunde", fr: "Optique et ophtalmologie", it: "Ottica e oftalmologia", nl: "Optiek en oogheelkunde", zh: "光学与眼科", hi: "ऑप्टिक्स एवं नेत्र विज्ञान", ko: "안경 및 안과", ja: "眼鏡・眼科" } },
  "medicina-estetica": { family: "salud", label: { es: "Medicina estética", pt: "Medicina estética", en: "Aesthetic medicine", de: "Ästhetische Medizin", fr: "Médecine esthétique", it: "Medicina estetica", nl: "Esthetische geneeskunde", zh: "医学美容", hi: "सौंदर्य चिकित्सा", ko: "미용 의학", ja: "美容医療" } },
  "farmacia": { family: "salud", label: { es: "Farmacia", pt: "Farmácia", en: "Pharmaceuticals", de: "Pharmazie", fr: "Pharmacie", it: "Farmacia", nl: "Farmacie", zh: "制药", hi: "फार्मास्युटिकल", ko: "제약", ja: "製薬" } },
  "veterinaria": { family: "salud", label: { es: "Veterinaria", pt: "Veterinária", en: "Veterinary", de: "Veterinärmedizin", fr: "Vétérinaire", it: "Veterinaria", nl: "Diergeneeskunde", zh: "兽医", hi: "पशु चिकित्सा", ko: "수의", ja: "動物医療" } },
  "congreso-medico": { family: "salud", label: { es: "Congreso médico", pt: "Congresso médico", en: "Medical congress", de: "Medizinkongress", fr: "Congrès médical", it: "Congresso medico", nl: "Medisch congres", zh: "医学大会", hi: "चिकित्सा सम्मेलन", ko: "의학 학술대회", ja: "医学会議" } },
  "digital-software": { family: "tecnologia", label: { es: "Tecnología digital y software", pt: "Tecnologia digital e software", en: "Digital tech & software", de: "Digitaltechnik und Software", fr: "Technologies numériques et logiciels", it: "Tecnologia digitale e software", nl: "Digitale technologie en software", zh: "数字技术与软件", hi: "डिजिटल तकनीक एवं सॉफ्टवेयर", ko: "디지털 기술 및 소프트웨어", ja: "デジタル技術・ソフトウェア" } },
  "audiovisual": { family: "tecnologia", label: { es: "Audiovisual y VFX", pt: "Audiovisual e VFX", en: "Audiovisual & VFX", de: "Audiovisuelles und VFX", fr: "Audiovisuel et VFX", it: "Audiovisivo e VFX", nl: "Audiovisueel en VFX", zh: "视听与视觉特效", hi: "ऑडियोविज़ुअल एवं VFX", ko: "영상 및 VFX", ja: "映像・VFX" } },
  "fotonica": { family: "tecnologia", label: { es: "Fotónica y optoelectrónica", pt: "Fotónica e optoeletrónica", en: "Photonics & optoelectronics", de: "Photonik und Optoelektronik", fr: "Photonique et optoélectronique", it: "Fotonica e optoelettronica", nl: "Fotonica en opto-elektronica", zh: "光子学与光电子", hi: "फोटोनिक्स एवं ऑप्टोइलेक्ट्रॉनिक्स", ko: "포토닉스 및 광전자", ja: "フォトニクス・オプトエレクトロニクス" } },
  "smart-city": { family: "tecnologia", label: { es: "Smart city", pt: "Smart city", en: "Smart city", de: "Smart City", fr: "Smart city", it: "Smart city", nl: "Smart city", zh: "智慧城市", hi: "स्मार्ट सिटी", ko: "스마트 시티", ja: "スマートシティ" } },
  "packaging": { family: "comercio", label: { es: "Packaging y envase", pt: "Packaging e embalagem", en: "Packaging", de: "Verpackung", fr: "Packaging et emballage", it: "Packaging e imballaggio", nl: "Verpakking", zh: "包装与封装", hi: "पैकेजिंग एवं पैकिंग", ko: "패키징 및 포장", ja: "パッケージ・包装" } },
  "papel-carton": { family: "industria", label: { es: "Papel y cartón", pt: "Papel e cartão", en: "Paper & board", de: "Papier & Karton", fr: "Papier et carton", it: "Carta e cartone", nl: "Papier & karton", zh: "纸张与纸板", hi: "कागज़ एवं कार्डबोर्ड", ko: "제지 및 판지", ja: "紙・板紙" } },
  "seguridad": { family: "industria", label: { es: "Seguridad", pt: "Segurança", en: "Security & safety", de: "Sicherheit", fr: "Sécurité", it: "Sicurezza", nl: "Veiligheid", zh: "安全防护", hi: "सुरक्षा", ko: "보안·안전", ja: "セキュリティ・安全" } },
  "moda-textil": { family: "comercio", label: { es: "Moda y textil", pt: "Moda e têxtil", en: "Fashion & textiles", de: "Mode und Textil", fr: "Mode et textile", it: "Moda e tessile", nl: "Mode en textiel", zh: "时尚与纺织", hi: "फैशन एवं वस्त्र", ko: "패션 및 섬유", ja: "ファッション・繊維" } },
  "regalo-decoracion": { family: "comercio", label: { es: "Regalo y decoración", pt: "Presentes e decoração", en: "Gifts & home décor", de: "Geschenkartikel und Dekoration", fr: "Cadeau et décoration", it: "Regalo e decorazione", nl: "Cadeau en decoratie", zh: "礼品与装饰", hi: "उपहार एवं सजावट", ko: "선물 및 인테리어", ja: "ギフト・インテリア" } },
  "joyeria": { family: "comercio", label: { es: "Joyería y bisutería", pt: "Joalharia e bijutaria", en: "Jewellery & costume jewellery", de: "Schmuck und Modeschmuck", fr: "Bijouterie et joaillerie", it: "Gioielleria e bigiotteria", nl: "Juwelen en sieraden", zh: "珠宝与饰品", hi: "आभूषण एवं इमिटेशन ज्वेलरी", ko: "주얼리 및 액세서리", ja: "ジュエリー・アクセサリー" } },
  "construccion": { family: "construccion", label: { es: "Construcción", pt: "Construção", en: "Construction", de: "Bauwesen", fr: "Construction", it: "Edilizia", nl: "Bouw", zh: "建筑", hi: "निर्माण", ko: "건설", ja: "建設" } },
  "ventanas-cerramientos": { family: "construccion", label: { es: "Ventanas y cerramientos", pt: "Janelas e caixilharia", en: "Windows & façades", de: "Fenster und Fassaden", fr: "Fenêtres et menuiseries", it: "Serramenti e infissi", nl: "Ramen en gevelsluitingen", zh: "门窗与幕墙", hi: "खिड़कियां एवं क्लोज़र", ko: "창호 및 외장", ja: "窓・建具" } },
  "puertas": { family: "construccion", label: { es: "Puertas", pt: "Portas", en: "Doors", de: "Türen", fr: "Portes", it: "Porte", nl: "Deuren", zh: "门业", hi: "दरवाज़े", ko: "도어", ja: "ドア" } },
  "turismo": { family: "turismo", label: { es: "Turismo", pt: "Turismo", en: "Tourism", de: "Tourismus", fr: "Tourisme", it: "Turismo", nl: "Toerisme", zh: "旅游", hi: "पर्यटन", ko: "관광", ja: "観光" } },
  "gastronomia-hosteleria": { family: "turismo", label: { es: "Gastronomía y hostelería", pt: "Gastronomia e hotelaria", en: "Gastronomy & hospitality", de: "Gastronomie und Hotellerie", fr: "Gastronomie et hôtellerie-restauration", it: "Gastronomia e ristorazione", nl: "Gastronomie en horeca", zh: "餐饮与酒店", hi: "गैस्ट्रोनॉमी एवं आतिथ्य", ko: "외식 및 호텔", ja: "美食・外食" } },
  "automocion": { family: "transporte", label: { es: "Automoción", pt: "Automóvel", en: "Automotive", de: "Automobil", fr: "Automobile", it: "Automotive", nl: "Automotive", zh: "汽车", hi: "ऑटोमोटिव", ko: "자동차", ja: "自動車" } },
  "naval": { family: "transporte", label: { es: "Naval", pt: "Naval", en: "Naval & shipbuilding", de: "Schiffbau", fr: "Naval", it: "Navale", nl: "Scheepvaart", zh: "船舶", hi: "जहाज़ निर्माण", ko: "조선", ja: "造船" } },
  "aeronautica": { family: "transporte", label: { es: "Aeronáutica", pt: "Aeronáutica", en: "Aerospace", de: "Luft- und Raumfahrt", fr: "Aéronautique", it: "Aeronautica", nl: "Luchtvaart", zh: "航空", hi: "एयरोनॉटिक्स", ko: "항공우주", ja: "航空" } },
  "transporte": { family: "transporte", label: { es: "Transporte y logística", pt: "Transporte e logística", en: "Transport & logistics", de: "Transport und Logistik", fr: "Transport et logistique", it: "Trasporti e logistica", nl: "Transport en logistiek", zh: "运输与物流", hi: "परिवहन एवं लॉजिस्टिक्स", ko: "운송 및 물류", ja: "運輸・物流" } },
  "movilidad": { family: "transporte", label: { es: "Movilidad, ITS y tráfico", pt: "Mobilidade, ITS e tráfego", en: "Mobility, ITS & traffic", de: "Mobilität, ITS & Verkehr", fr: "Mobilité, ITS et trafic", it: "Mobilità, ITS e traffico", nl: "Mobiliteit, ITS & verkeer", zh: "出行、ITS 与交通", hi: "गतिशीलता, ITS एवं यातायात", ko: "모빌리티, ITS 및 교통", ja: "モビリティ・ITS・交通" } },
  "vino": { family: "enologia", label: { es: "Vino y enología", pt: "Vinho e enologia", en: "Wine & oenology", de: "Wein und Önologie", fr: "Vin et œnologie", it: "Vino ed enologia", nl: "Wijn en oenologie", zh: "葡萄酒与酿酒", hi: "वाइन एवं एनोलॉजी", ko: "와인 및 양조", ja: "ワイン・醸造" } },
  "equipamiento-vino": { family: "enologia", label: { es: "Equipamiento del vino", pt: "Equipamento vínico", en: "Winemaking equipment", de: "Weinkellereitechnik", fr: "Équipement vinicole", it: "Attrezzature per il vino", nl: "Wijnuitrusting", zh: "葡萄酒酿造设备", hi: "वाइन उपकरण", ko: "와인 설비", ja: "ワイン関連設備" } },
  "cultura-arte": { family: "ocio", label: { es: "Cultura y arte", pt: "Cultura e arte", en: "Culture & art", de: "Kultur und Kunst", fr: "Culture et art", it: "Cultura e arte", nl: "Cultuur en kunst", zh: "文化与艺术", hi: "संस्कृति एवं कला", ko: "문화 및 예술", ja: "文化・芸術" } },
  "pop-videojuegos": { family: "ocio", label: { es: "Cultura pop y videojuegos", pt: "Cultura pop e videojogos", en: "Pop culture & video games", de: "Popkultur und Videospiele", fr: "Culture pop et jeux vidéo", it: "Cultura pop e videogiochi", nl: "Popcultuur en games", zh: "流行文化与电子游戏", hi: "पॉप संस्कृति एवं वीडियो गेम", ko: "대중문화 및 게임", ja: "ポップカルチャー・ゲーム" } },
  "mascotas": { family: "ocio", label: { es: "Mascotas", pt: "Animais de estimação", en: "Pets", de: "Heimtiere", fr: "Animaux de compagnie", it: "Animali da compagnia", nl: "Huisdieren", zh: "宠物", hi: "पालतू पशु", ko: "반려동물", ja: "ペット" } },
  "belleza-peluqueria": { family: "belleza", label: { es: "Belleza y peluquería", pt: "Beleza e cabeleireiro", en: "Beauty & hairdressing", de: "Beauty und Friseurhandwerk", fr: "Beauté et coiffure", it: "Bellezza e acconciatura", nl: "Schoonheid en kappers", zh: "美容与美发", hi: "सौंदर्य एवं हेयरड्रेसिंग", ko: "뷰티 및 헤어", ja: "美容・ヘアサロン" } },
  "estetica": { family: "belleza", label: { es: "Estética", pt: "Estética", en: "Aesthetics", de: "Kosmetik", fr: "Esthétique", it: "Estetica", nl: "Esthetiek", zh: "美容护理", hi: "एस्थेटिक्स", ko: "에스테틱", ja: "エステティック" } },
  "multisectorial": { family: "multi", label: { es: "Multisectorial", pt: "Multissetorial", en: "Multi-sector", de: "Branchenübergreifend", fr: "Multisectoriel", it: "Multisettoriale", nl: "Multisectoraal", zh: "综合行业", hi: "बहु-क्षेत्रीय", ko: "종합 산업", ja: "総合展示会" } },
  "congreso-profesional": { family: "multi", label: { es: "Congreso profesional", pt: "Congresso profissional", en: "Professional congress", de: "Fachkongress", fr: "Congrès professionnel", it: "Congresso professionale", nl: "Vakcongres", zh: "专业大会", hi: "पेशेवर सम्मेलन", ko: "전문 학술대회", ja: "専門学会・会議" } },
};
export const fairActivities = {
  "stand-artesantander": ["cultura-arte"],
  "stand-biocantabria-santander": ["ecologico", "alimentacion"],
  "stand-feria-apicola-cantabria-torrelavega": ["ganaderia", "alimentacion"],
  "stand-feria-concesionarios-torrelavega": ["automocion"],
  "stand-fidma-gijon": ["multisectorial"],
  "stand-agropec-gijon": ["ganaderia", "agricultura-maquinaria"],
  "stand-salon-competicion-asturias-gijon": ["automocion"],
  "stand-asturforesta-tineo": ["agricultura-maquinaria", "ecologico"],
  "stand-feria-muestras-tineo": ["multisectorial"],
  "stand-agroalimentaria-vegadeo": ["alimentacion", "ecologico"],
  "stand-cargo-freight-portugal-summit": ["transporte"],
  "stand-techlogistics-lisboa": ["transporte"],
  "stand-scm-conference": ["transporte"],
  "stand-airspace-world-lisboa": ["aeronautica"],
  "stand-expomadeira": ["multisectorial"],
  "stand-feira-agropecuaria-madeira": ["agricultura-maquinaria", "ganaderia"],
  "stand-feira-emprego-formacao-empreendedorismo-madeira": ["multisectorial"],
  "stand-feira-empreendedorismo-madeira": ["digital-software"],
  "stand-festa-vinho-madeira": ["vino"],
  "stand-cider-fest-madeira": ["gastronomia-hosteleria"],
  "stand-feaga-fuerteventura": ["agricultura-maquinaria", "ganaderia"],
  "stand-gastrocanarias-tenerife": ["gastronomia-hosteleria"],
  "stand-gran-canaria-me-gusta": ["alimentacion", "gastronomia-hosteleria"],
  "stand-fimar-las-palmas": ["pesca-mar", "naval"],
  "stand-canagua-energia-gran-canaria": ["energia","ecologico"],
  "stand-salon-atlantico-logistica-transporte": ["logistica", "transporte"],
  "stand-moda-tenerife": ["moda-textil"],
  "stand-expodeca": ["regalo-decoracion"],
  "stand-feboda": ["multisectorial"],
  "stand-canarias-destino-startup": ["digital-software"],
  "stand-feria-empresarial-norte-gran-canaria": ["multisectorial"],
  "stand-futuralia-lisboa": ["multisectorial"],
  "stand-seafood-expo-global-barcelona": ["pesca-mar", "alimentacion"],
  "stand-sil-barcelona": ["logistica"],
  "stand-automobile-barcelona": ["automocion"],
  "stand-piscina-wellness-barcelona": ["construccion", "turismo"],
  "stand-municipalia-lleida": ["construccion", "smart-city"],
  "stand-fira-sant-miquel-lleida": ["agricultura-maquinaria"],
  "stand-forum-gastronomic-girona": ["gastronomia-hosteleria", "alimentacion"],
  "stand-mindtech-vigo": ["metal-subcontratacion"],
  "stand-galicia-escena-pro-santiago-de-compostela": ["cultura-arte"],
  "stand-semana-verde-galicia-silleda": ["multisectorial", "ganaderia"],
  "stand-turexpo-galicia-silleda": ["turismo"],
  "stand-xantar-ourense": ["gastronomia-hosteleria"],
  "stand-termatalia-ourense": ["turismo"],
  "stand-galiforest-boqueixon": ["agricultura-maquinaria", "ecologico"],
  "stand-infoagro-exhibition-aguadulce": ["agricultura-maquinaria", "ecologico"],
  "stand-expolevante-el-ejido": ["agricultura-maquinaria"],
  "stand-sun-blue-congress-almeria": ["turismo", "ecologico"],
  "stand-expoliva-jaen": ["alimentacion", "agricultura-maquinaria"],
  "stand-ibercaza-jaen": ["ecologico", "pesca-mar"],
  "stand-feria-de-los-pueblos-jaen": ["multisectorial", "turismo"],
  "stand-congreso-internacional-frutos-rojos-huelva": ["alimentacion", "agricultura-maquinaria"],
  "stand-feria-jamon-cerdo-iberico-aracena": ["alimentacion", "ganaderia"],
  "stand-feria-gamba-chirla-boqueron-punta-umbria": ["pesca-mar", "alimentacion"],
  "stand-intercaza-cordoba": ["ecologico", "pesca-mar"],
  "stand-feria-agroganadera-pedroches-pozoblanco": ["ganaderia", "agricultura-maquinaria"],
  "stand-feria-jamon-bellota-dop-pedroches-villanueva-cordoba": ["alimentacion", "ganaderia"],
  "stand-feria-general-muestras-armilla": ["multisectorial"],
  "stand-feria-de-la-ciencia-granada": ["digital-software"],
  "stand-concab-granada": ["ganaderia"],
  "stand-belmoda-granada": ["moda-textil", "gastronomia-hosteleria", "regalo-decoracion"],
  "stand-sabores-nuestra-tierra-granada": ["alimentacion", "gastronomia-hosteleria"],
  "stand-feria-pueblos-granada": ["multisectorial", "turismo"],
  "stand-blue-zone-forum-navalia-meeting-cadiz": ["naval", "energia"],
  "stand-feria-del-caballo-jerez": ["turismo"],
  "stand-fegasur-jerez": ["ganaderia"],
  "stand-futurmoda-elche": ["moda-textil", "maquinaria-industrial"],
  "stand-firauto-elche": ["automocion"],
  "stand-alicante-gastronomica": ["gastronomia-hosteleria"],
  "stand-fame-innowa-torre-pacheco": ["agricultura-maquinaria", "ganaderia"],
  "stand-equimur-torre-pacheco": ["ganaderia"],
  "stand-hortifruit-torre-pacheco": ["agricultura-maquinaria", "alimentacion"],
  "stand-fecons-torre-pacheco": ["construccion"],
  "stands-agroexpo-feval-don-benito": ["agricultura-maquinaria"],
  "stand-feria-de-fp-badajoz": ["multisectorial"],
  "stand-feria-de-los-mayores-de-extremadura-badajoz": ["multisectorial"],
  "stand-fio-monfrague": ["alimentacion"],
  "stand-feria-de-belleza-moda-y-cosmetica-badajoz": ["belleza-peluqueria","estetica","moda-textil"],
  "stand-vinac-almendralejo": ["vino","equipamiento-vino"],
  "stand-artexania-plasencia": ["cultura-arte"],
  "stand-fenavin-match-ciudad-real": ["vino"],
  "stand-ferduque-ciudad-real": ["ganaderia", "agricultura-maquinaria"],
  "stand-intur-valladolid": ["turismo"],
  "stand-fromago-cheese-experience-zamora": ["alimentacion"],
  "stand-expovicaman-albacete": ["agricultura-maquinaria", "ganaderia"],
  "stand-farcama-toledo": ["cultura-arte"],
  "stand-feria-artesania-valladolid": ["cultura-arte"],
  "stand-feria-vino-do-bierzo-cacabelos": ["vino"],
  "stand-feria-churra-palencia": ["ganaderia"],
  "stand-jec-world-paris": ["aeronautica", "maquinaria-industrial"],
  "stand-logimat-stuttgart": ["logistica"],
  "stand-global-industrie-paris": ["maquinaria-industrial"],
  "stand-ecuextre-badajoz": ["multisectorial"],
  "stand-hannover-messe": ["maquinaria-industrial"],
  "stand-sagalexpo-lisboa": ["multisectorial"],
  "stand-sil-lisboa": ["construccion"],
  "stand-fercam-manzanares-ciudad-real": ["agricultura-maquinaria"],
  "stand-portugal-smart-cities-summit": ["digital-software","smart-city","congreso-profesional","movilidad","naval"],
  "stand-arcolisboa": ["cultura-arte"],
  "stand-des-malaga": ["digital-software"],
  "stand-cm-malaga": ["multisectorial"],
  "stand-foro-greencities-malaga": ["digital-software","smart-city"],
  "stand-fercatur-ciudad-real": ["multisectorial"],
  "stand-feciex-badajoz": ["multisectorial"],
  "stand-san-diego-comic-con-malaga": ["pop-videojuegos"],
  "stand-expo-agritech-malaga": ["agricultura-maquinaria"],
  "stand-simed-malaga": ["construccion"],
  "stand-fehispor-badajoz": ["multisectorial"],
  "stand-amb-stuttgart": ["maquinaria-industrial"],
  "stand-iberocio-badajoz": ["cultura-arte"],
  "stand-sps-nuremberg": ["maquinaria-industrial"],
  "stand-automatica-munich": ["maquinaria-industrial", "digital-software"],
  "stand-sirha-lyon": ["gastronomia-hosteleria"],
  "stand-global-industrie-lyon": ["maquinaria-industrial", "metal-subcontratacion"],
  "stand-pollutec-lyon": ["energia", "ecologico"],
  "stand-piscine-global-lyon": ["construccion", "turismo"],
  "stand-preventica-lyon": ["congreso-profesional"],
  "stand-prod-pack-lyon": ["alimentacion", "packaging", "maquinaria-industrial"],
  "stand-bepositive-lyon": ["energia", "construccion"],
  "stand-sommet-elevage-clermont-ferrand": ["ganaderia", "agricultura-maquinaria", "congreso-profesional"],
  "stand-mountain-planet-grenoble": ["turismo", "construccion", "congreso-profesional"],
  "stand-sepem-industries-sud-est-grenoble": ["maquinaria-industrial", "logistica", "congreso-profesional"],
  "stand-sitevi-montpellier": ["equipamiento-vino", "agricultura-maquinaria"],
  "stand-millesime-bio-montpellier": ["vino", "ecologico"],
  "stand-sett-montpellier": ["turismo", "construccion"],
  "stand-energaia-montpellier": ["energia", "ecologico"],
  "stand-siprho-montpellier": ["gastronomia-hosteleria"],
  "stand-ais-montpellier": ["farmacia", "congreso-profesional"],
  "stand-agecotel-nice": ["gastronomia-hosteleria"],
  "stand-nice-boating-tomorrow": ["naval", "ecologico"],
  "stand-ibt-cote-azur": ["construccion", "maquinaria-industrial"],
  "stand-entreprenariales-nice": ["congreso-profesional"],
  "stand-solucop-nice": ["construccion"],
  "stand-bauma-munich": ["maquinaria-industrial"],
  "stand-fireca-sevilla": ["multisectorial"],
  "stand-mmh-sevilla": ["maquinaria-industrial","metal-subcontratacion"],
  "stand-conxemar-vigo": ["alimentacion","pesca-mar"],
  "stand-veteco-madrid": ["ventanas-cerramientos"],
  "stand-piscimad-madrid": ["construccion"],
  "stand-greencities-malaga": ["digital-software","smart-city"],
  "stand-iberpet-madrid": ["mascotas"],
  "stand-ht-malaga": ["gastronomia-hosteleria"],
  "stand-eurosatory-paris": ["aeronautica"],
  "stand-empack-madrid": ["packaging"],
  "stand-hygienalia-madrid": ["limpieza-higiene","maquinaria-industrial"],
  "stand-expoquimia-barcelona": ["packaging", "maquinaria-industrial"],
  "stand-mwc-barcelona": ["digital-software"],
  "stand-ise-barcelona": ["audiovisual"],
  "stand-alimentaria-barcelona": ["alimentacion"],
  "stand-hispack-barcelona": ["packaging"],
  "stand-labelexpo-barcelona": ["packaging"],
  "stand-hostelco-barcelona": ["gastronomia-hosteleria"],
  "stand-smart-city-expo-world-congress-barcelona": ["digital-software","smart-city","congreso-profesional","movilidad"],
  "stand-construmat-barcelona": ["construccion"],
  "stand-iot-solutions-world-congress-barcelona": ["digital-software","congreso-profesional"],
  "stand-smart-doors-madrid": ["smart-city","puertas"],
  "stand-equiplast-barcelona": ["packaging", "maquinaria-industrial"],
  "stand-tis-sevilla": ["digital-software"],
  "stand-autentica-sevilla": ["multisectorial"],
  "stand-esicm-lives-lisboa": ["congreso-medico"],
  "stand-cascais-international-health-forum": ["congreso-medico"],
  "stand-lisbon-food-affair": ["alimentacion"],
  "stand-snackex-lisboa": ["alimentacion"],
  "stand-gse-expo-lisboa": ["aeronautica"],
  "stand-esra-congress-lisboa": ["congreso-medico","congreso-profesional"],
  "stand-world-aviation-festival-lisboa": ["aeronautica"],
  "stand-pegs-europe-lisboa": ["congreso-medico"],
  "stand-btl-lisboa": ["turismo"],
  "stand-lisboa-games-week": ["pop-videojuegos","digital-software"],
  "stand-nauticampo-lisboa": ["nautica","turismo"],
  "stand-smopyc-zaragoza": ["maquinaria-industrial"],
  "stand-smagua-zaragoza": ["ecologico"],
  "stand-aratur-zaragoza": ["turismo","gastronomia-hosteleria"],
  "stand-expofimer-zaragoza": ["energia"],
  "stand-spaper-zaragoza": ["papel-carton","maquinaria-industrial"],
  "stand-fima-zaragoza": ["agricultura-maquinaria"],
  "stand-feria-internacional-ganadera-zafra": ["ganaderia","multisectorial","agricultura-maquinaria"],
  "stand-feria-internacional-ganadera-trujillo": ["ganaderia","multisectorial","agricultura-maquinaria"],
  "stand-feria-nacional-queso-trujillo": ["alimentacion","gastronomia-hosteleria"],
  "stands-agroexpo-don-benito": ["agricultura-maquinaria","ganaderia","multisectorial"],
  "stand-web-summit-lisboa": ["digital-software","congreso-profesional"],
  "stand-tektonica-lisboa": ["construccion"],
  "stands-biemh-bilbao": ["maquinaria-industrial"],
  "stands-subcontratacion-bilbao": ["metal-subcontratacion"],
  "stand-addit3d-bilbao": ["metal-subcontratacion"],
  "stand-bedigital-bilbao": ["digital-software"],
  "stands-pumps-valves-bilbao": ["maquinaria-industrial"],
  "stands-maintenance-bilbao": ["maquinaria-industrial"],
  "stand-fruit-attraction-madrid": ["alimentacion"],
  "stand-salon-look-madrid": ["estetica","belleza-peluqueria"],
  "stand-cosmobeauty-barcelona": ["belleza-peluqueria","estetica","medicina-estetica"],
  "stand-beauty-forum-valencia": ["estetica","belleza-peluqueria"],
  "stand-expomedes-madrid": ["medicina-estetica","estetica"],
  "stand-in-beauty-lisboa": ["belleza-peluqueria","estetica"],
  "stand-madrid-tech-show": ["digital-software"],
  "stand-the-district-madrid": ["construccion"],
  "stand-intergift-madrid": ["regalo-decoracion"],
  "stand-momad-madrid": ["moda-textil"],
  "stand-madridjoya-madrid": ["joyeria"],
  "stand-bisutex-madrid": ["joyeria"],
  "stand-fitur-madrid": ["turismo"],
  "stand-advanced-manufacturing-madrid": ["maquinaria-industrial","metal-subcontratacion"],
  "stand-hip-madrid": ["gastronomia-hosteleria","alimentacion"],
  "stand-meat-attraction-madrid": ["alimentacion"],
  "stand-sicur-madrid": ["seguridad","maquinaria-industrial"],
  "stand-arcomadrid": ["cultura-arte"],
  "stand-salon-gourmets-madrid": ["alimentacion","gastronomia-hosteleria","vino"],
  "stand-rebuild-madrid": ["construccion"],
  "stand-madrid-fusion": ["turismo"],
  "stand-expofranquicia-madrid": ["multisectorial"],
  "stand-concreta-oporto": ["construccion"],
  "stand-expocosmetica-oporto": ["belleza-peluqueria","estetica"],
  "stand-empack-oporto": ["packaging", "transporte"],
  "stand-itf-intertex-oporto": ["maquinaria-industrial"],
  "stand-expomecanica-oporto": ["transporte"],
  "stand-emaf-oporto": ["maquinaria-industrial"],
  "stand-portojoia-oporto": ["joyeria"],
  "stand-decor-hotel-oporto": ["turismo"],
  "stand-expocarne-oporto": ["alimentacion"],
  "stand-cevisama-valencia": ["construccion"],
  "stand-habitat-valencia": ["packaging"],
  "stand-textilhogar-valencia": ["moda-textil"],
  "stand-espacio-cocina-sici-valencia": ["packaging"],
  "stand-fimma-maderalia-valencia": ["maquinaria-industrial"],
  "stand-iberflora-valencia": ["alimentacion"],
  "stand-gastronoma-valencia": ["gastronomia-hosteleria"],
  "stand-eurobrico-valencia": ["packaging"],
  "stand-palma-international-boat-show": ["transporte"],
  "stand-palma-superyacht-village": ["transporte"],
  "stand-baleart-mallorca": ["cultura-arte"],
  "stand-dijous-bo-mallorca": ["multisectorial"],
  "stands-figan-zaragoza": ["alimentacion"],
  "stand-enomaq-zaragoza": ["vino","equipamiento-vino"],
  "stand-oleomaq-zaragoza": ["alimentacion"],
  "stand-tecnovid-zaragoza": ["vino","equipamiento-vino"],
  "stand-navalia-vigo": ["naval"],
  "stand-world-maritime-week-bilbao": ["naval","energia"],
  "stand-marine-energy-week-bilbao": ["naval","energia"],
  "stand-ferroforma-bilbao": ["maquinaria-industrial","metal-subcontratacion"],
  "stand-sinaval-bilbao": ["naval"],
  "stand-eurofishing-bilbao": ["pesca-mar","naval"],
  "stand-pick-pack-bilbao": ["packaging","logistica","alimentacion"],
  "stand-futureport-bilbao": ["naval","logistica"],
  "stand-steel-tech-bilbao": ["metal-subcontratacion","maquinaria-industrial"],
  "stand-expovacaciones-bilbao": ["turismo"],
  "stand-egurtek-bilbao": ["construccion","ecologico"],
  "stand-plus-industry-bilbao": ["maquinaria-industrial","metal-subcontratacion"],
  "stand-wear-bilbao": ["digital-software","maquinaria-industrial"],
  "stand-f4f-expo-foodtech-bilbao": ["alimentacion","maquinaria-industrial"],
  "stand-gustoko-bilbao": ["alimentacion","gastronomia-hosteleria"],
  "stand-blue-zone-forum": ["naval"],
  "stand-sea-portugal": ["naval"],
  "stand-feira-sao-mateus-elvas": ["multisectorial","gastronomia-hosteleria"],
  "stand-feira-nacional-agricultura-santarem": ["agricultura-maquinaria","ganaderia","alimentacion"],
  "stand-fersant-santarem": ["multisectorial"],
  "stand-agroglobal-santarem": ["agricultura-maquinaria"],
  "stand-lusoflora-santarem": ["agricultura-maquinaria"],
  "stand-nortrans-vigo": ["transporte"],
  "stand-moldplas-batalha": ["maquinaria-industrial"],
  "stand-expometal-batalha": ["metal-subcontratacion"],
  "stand-stone-iberica-batalha": ["construccion"],
  "stand-vidrotec-batalha": ["construccion"],
  "stand-decorhotel-batalha": ["turismo"],
  "stand-ovibeja-beja": ["alimentacion"],
  "stand-fatacil-lagoa": ["multisectorial"],
  "stand-faceco-moncarapacho": ["multisectorial"],
  "stand-feira-de-sao-martinho-portimao": ["multisectorial"],
  "stand-feira-daires-viana-do-alentejo": ["multisectorial"],
  "stand-fairway-santiago-de-compostela": ["turismo"],
  "stand-maker-faire-galicia-santiago-de-compostela": ["digital-software"],
  "stand-gedet-santiago-de-compostela": ["congreso-medico"],
  "stand-semergen-santiago-de-compostela": ["medicina-estetica","congreso-profesional"],
  "stand-sesmi-santiago-de-compostela": ["congreso-medico"],
  "stand-forum-gastronomico-a-coruna": ["gastronomia-hosteleria"],
  "stand-mundos-digitales-a-coruna": ["digital-software","audiovisual"],
  "stand-biocultura-a-coruna": ["ecologico"],
  "stand-agraria-valladolid": ["agricultura-maquinaria"],
  "stand-agrovid-valladolid": ["agricultura-maquinaria", "equipamiento-vino"],
  "stand-aviforum-valladolid": ["ganaderia", "veterinaria"],
  "stand-fimascota-valladolid": ["mascotas"],
  "stand-salamaq-salamanca": ["ganaderia"],
  "stand-salon-automovil-salamanca": ["automocion"],
  "stand-congreso-alineadores-salamanca": ["dental","congreso-profesional"],
  "stand-expodental-madrid": ["dental"],
  "stand-forum-dental-mediterraneo-barcelona": ["dental"],
  "stand-expooptica-madrid": ["optica-oftalmologia"],
  "stand-optom-madrid": ["optica-oftalmologia"],
  "stand-cioc-lisboa": ["optica-oftalmologia"],
  "stand-ciocv-braga": ["optica-oftalmologia"],
  "stand-foyer-health-beauty-lisboa": ["medicina-estetica","estetica","congreso-profesional"],
  "stand-seme-medicina-estetica": ["medicina-estetica","estetica","congreso-profesional"],
  "stand-secpre-cirugia-plastica": ["medicina-estetica","congreso-medico","congreso-profesional"],
  "stand-spcpre-cirugia-plastica-portugal": ["medicina-estetica","congreso-medico","congreso-profesional"],
  "stand-spme-medicina-estetica-portugal": ["medicina-estetica","estetica","congreso-profesional"],
  "stand-seo-oftalmologia": ["optica-oftalmologia","congreso-profesional"],
  "stand-infarma": ["farmacia"],
  "stand-farmaforum-madrid": ["farmacia"],
  "stand-congreso-farmaceuticos-comunitarios": ["farmacia","congreso-profesional"],
  "stand-congreso-sefh-farmacia-hospitalaria": ["farmacia","congreso-medico","congreso-profesional"],
  "stand-secoir-cirugia-ocular": ["optica-oftalmologia","congreso-profesional"],
  "stand-rno-reunion-nacional-optica": ["optica-oftalmologia","fotonica","congreso-profesional"],
  "stand-optoel-optoelectronica": ["fotonica","congreso-profesional"],
  "stand-set-trasplante": ["congreso-medico","congreso-profesional"],
  "stand-salon-automovil-merida": ["automocion"],
  "stand-feria-bodas-hogar-merida": ["regalo-decoracion"],
  "stand-coleccionismo-emerita-augusta-merida": ["cultura-arte"],
  "stand-feturex-merida": ["turismo"],
  "stand-salon-gas-renovable-valladolid": ["energia"],
  "stand-genera-madrid": ["energia"],
  "stand-solar-storage-live-espana-valencia": ["energia"],
  "stand-lisbon-energy-summit-lisboa": ["energia","congreso-profesional"],
  "stand-re-plus-portugal-oporto": ["energia","congreso-profesional"],
  "stand-eletrica-oporto": ["energia"],
  "stand-enerh2o-oporto": ["energia"],
  "stand-essencia-do-vinho-porto": ["vino"],
  "stand-simplesmente-vinho-porto": ["vino"],
  "stand-essencia-do-vinho-lisboa": ["vino"],
  "stand-encontro-vinhos-sabores-lisboa": ["vino"],
  "stand-vinhos-de-portugal-lisboa": ["vino"],
  "stand-vinipax-beja": ["vino"],
  "stand-barcelona-wine-week": ["vino"],
  "stand-salon-vinos-aragon-zaragoza": ["vino"],
  "stand-wine-paris": ["vino"],
  "stand-prowein-dusseldorf": ["vino"],
  "stand-its-european-congress": ["movilidad","smart-city","congreso-profesional"],
  "stand-congreso-its-espana": ["movilidad","congreso-profesional"],
  "stand-trafic-madrid": ["movilidad"],
  "stand-fiaa-madrid": ["transporte","movilidad","automocion"],
  "stand-global-mobility-call-madrid": ["movilidad","smart-city","congreso-profesional"],
  "stand-mubil-mobility-expo-irun": ["movilidad","energia"],
  "stand-unire-irun": ["metal-subcontratacion","maquinaria-industrial"],
  "stand-bioterra-irun": ["ecologico","alimentacion","construccion"],
  "stand-caravantur-irun": ["turismo","movilidad"],
  "stand-uhinak-irun": ["ecologico","pesca-mar"],
  "stand-go-mobility-irun": ["movilidad"],
  "stand-rioja-wine-trade-mission-logrono": ["vino"],
  "stand-planeta-rioja-logrono": ["vino"],
  "stand-feria-formacion-profesional-la-rioja-logrono": ["congreso-profesional","multisectorial"],
  "stand-feria-vehiculo-ocasion-logrono": ["automocion"],
  "stand-feria-maquinaria-agricola-alfaro": ["agricultura-maquinaria"],
  "stand-ferias-agroalimentarias-rioja-oriental-calahorra": ["alimentacion"],
  "stand-navartur-pamplona": ["turismo"],
  "stand-salon-estudiante-futuro-profesional-pamplona": ["congreso-profesional","multisectorial"],
  "stand-edifica-pamplona": ["construccion"],
  "stand-navarra-jobs-pamplona": ["congreso-profesional"],
  "stand-feria-navarra-ecologica-pamplona": ["ecologico","alimentacion"],
  "stand-navarra-wine-gastronomy-pamplona": ["vino","gastronomia-hosteleria"],
  "stand-feria-turismo-reyno-navarra-pamplona": ["turismo"],
  "stand-ardoaraba-vitoria": ["vino","gastronomia-hosteleria"],
  "stand-avanza-fp-alava-vitoria": ["congreso-profesional","multisectorial"],
  "stand-empleo-gune-vitoria": ["congreso-profesional"],
  "stand-feria-stocks-vitoria": ["moda-textil","regalo-decoracion"],
  "stand-lanberri-vitoria": ["cultura-arte"],
  "stand-espacio-ribera-aranda": ["vino"],
  "stand-premios-envero-enverofest-aranda": ["vino","gastronomia-hosteleria"],
  "stand-congreso-la-cierna-aranda": ["vino","congreso-profesional"],
  "stand-douro-porto-wine-festival-regua": ["vino","gastronomia-hosteleria"],
  "stand-feira-vinhos-sabores-altos-regua": ["vino","gastronomia-hosteleria"],
  "stand-festa-saberes-sabores-douro-regua": ["vino","gastronomia-hosteleria"],
  "stand-sieb-valladolid": ["equipamiento-vino"],
  "stand-enotecnica-olitecnica-oporto": ["vino","equipamiento-vino"],
  "stand-enoforum-zaragoza": ["vino","equipamiento-vino"],
  "stand-ficor-san-vicente-alcantara": ["equipamiento-vino","packaging"],
  "stand-horeca-baleares-mallorca": ["gastronomia-hosteleria"],
  "stand-fira-vi-pollenca-mallorca": ["vino"],
  "stand-wine-days-binissalem-mallorca": ["vino","gastronomia-hosteleria"],
  "stand-fira-sipia-alcudia-mallorca": ["gastronomia-hosteleria","pesca-mar"],
  "stand-horeca-baleares-ibiza": ["gastronomia-hosteleria"],
  "stand-fira-mar-ibiza": ["naval","pesca-mar"],
  "stand-feria-stocks-ibiza": ["moda-textil","regalo-decoracion"],
  "stand-horeca-baleares-menorca": ["gastronomia-hosteleria"],
  "stand-fira-camp-alaior-menorca": ["ganaderia","alimentacion"],
  "stand-arrels-menorca": ["alimentacion","gastronomia-hosteleria"],
  "stand-bet-on-ceuta": ["digital-software","smart-city"],
  "stand-ceuta-impulsa": ["multisectorial","congreso-profesional"],
  "stand-odissea-economia-azul-ceuta": ["pesca-mar","multisectorial"],
  "stand-feria-oportunidades-economicas-melilla": ["multisectorial","congreso-profesional"],
  "stand-feria-representacion-intercultural-melilla": ["cultura-arte","multisectorial"],
  "stand-eventos-empresariales-proyecto-melilla": ["congreso-profesional","multisectorial"],
  "stand-maroc-in-mode-mim-tanger": ["moda-textil"],
  "stand-tanger-nexus": ["multisectorial","congreso-profesional"],
  "stand-tanger-fashion-week": ["moda-textil","joyeria"],
  "stand-amith-nord-tanger": ["moda-textil"],
  "stand-eventos-industriales-tanger-med": ["logistica","maquinaria-industrial"],
  "stand-fira-andorra-la-vella": ["multisectorial","turismo"],
  "stand-enfirat-encamp": ["multisectorial","automocion"],
  "stand-andorra-taste": ["gastronomia-hosteleria","congreso-profesional"],
  "stand-fira-del-vermut-andorra": ["vino","gastronomia-hosteleria"],
  "stand-fira-del-bestiar-ordino": ["ganaderia","alimentacion"],
  "stand-mercat-de-la-vall-andorra": ["regalo-decoracion","alimentacion","cultura-arte"],
  "stand-fira-outlet-soldeu": ["moda-textil","regalo-decoracion"],
  "stand-motortec-madrid": ["automocion","maquinaria-industrial"],
  "stand-feria-jamon-teruel": ["alimentacion","gastronomia-hosteleria"],
  "stand-expocalamocha": ["ganaderia","agricultura-maquinaria"],
  "stand-femoga-sarinena": ["agricultura-maquinaria","ganaderia"],
  "stand-ferma-barbastro": ["multisectorial","alimentacion"],
  "stand-agroalcaniz": ["agricultura-maquinaria","maquinaria-industrial"],
  "stand-foire-internationale-marseille": ["multisectorial"],
  "stand-euromaritime-marseille": ["naval", "logistica"],
  "stand-sirha-mediterranee-marseille": ["gastronomia-hosteleria", "alimentacion"],
  "stand-beauty-profs-marseille": ["belleza-peluqueria", "estetica"],
  "stand-savim-marseille": ["vino", "gastronomia-hosteleria"],
  "stand-salon-piscine-jardin-marseille": ["construccion"],
  "stand-solutions-cse-marseille": ["congreso-profesional", "multisectorial"],
  "stand-japan-expo-sud-marseille": ["pop-videojuegos"],
  "stand-herofestival-marseille": ["pop-videojuegos"],
  "stand-siac-marseille": ["cultura-arte"],
  "stand-cannes-yachting-festival": ["naval","turismo"],
  "stand-interior-exterior-design-meetings-cannes": ["regalo-decoracion","construccion"],
  "stand-mapic-cannes": ["congreso-profesional","regalo-decoracion"],
  "stand-mipim-cannes": ["construccion","congreso-profesional"],
  "stand-tfwa-cannes": ["regalo-decoracion","turismo"],
  "stand-medagri-avignon": ["agricultura-maquinaria","ganaderia"],
  "stand-foire-internationale-toulouse": ["multisectorial"],
  "stand-cfia-toulouse": ["alimentacion", "packaging", "maquinaria-industrial"],
  "stand-sepem-industries-toulouse": ["maquinaria-industrial", "metal-subcontratacion"],
  "stand-aerospace-test-development-show-toulouse": ["aeronautica"],
  "stand-aeromart-toulouse": ["aeronautica", "congreso-profesional"],
  "stand-siane-toulouse": ["maquinaria-industrial", "metal-subcontratacion"],
  "stand-smahrt-toulouse": ["gastronomia-hosteleria"],
  "stand-foire-exposition-perpignan": ["multisectorial"],
  "stand-medfel-perpignan": ["alimentacion", "agricultura-maquinaria", "logistica", "packaging", "congreso-profesional"],
  "stand-viv-habitat-perpignan": ["construccion", "regalo-decoracion"],
  "stand-tourisme-loisirs-perpignan": ["turismo"],
  "stand-eco-maison-perpignan": ["construccion", "ecologico"],
  "stand-retro-mecanic-perpignan": ["automocion"],
  "stand-salon-mariage-perpignan": ["moda-textil", "gastronomia-hosteleria"],
  "stand-foire-internationale-bordeaux": ["multisectorial"],
  "stand-vinitech-sifel-bordeaux": ["vino", "equipamiento-vino", "agricultura-maquinaria"],
  "stand-equitaine-bordeaux": ["ganaderia"],
  "stand-salon-agriculture-nouvelle-aquitaine-bordeaux": ["agricultura-maquinaria", "ganaderia"],
  "stand-art3f-bordeaux": ["cultura-arte"],
  "stand-grand-salon-habitat-bordeaux": ["construccion", "regalo-decoracion"],
  "stand-salon-vins-vignerons-independants-bordeaux": ["vino"],
  "stand-cycleau-nouvelle-aquitaine-bordeaux": ["energia", "construccion"],
  "stand-alina-bordeaux": ["alimentacion", "maquinaria-industrial"],
  "stand-preventica-bordeaux": ["congreso-profesional"],
  "stand-logismed-casablanca": ["logistica", "transporte", "congreso-profesional"],
  "stand-morocco-food-expo-casablanca": ["alimentacion"],
  "stand-siema-casablanca": ["alimentacion", "maquinaria-industrial"],
  "stand-siab-casablanca": ["alimentacion", "gastronomia-hosteleria"],
  "stand-elec-expo-casablanca": ["energia", "maquinaria-industrial"],
  "stand-ener-event-casablanca": ["energia"],
  "stand-plast-expo-casablanca": ["maquinaria-industrial"],
  "stand-pack-expo-casablanca": ["packaging"],
  "stand-sistep-casablanca": ["maquinaria-industrial", "metal-subcontratacion"],
  "stand-imme-casablanca": ["metal-subcontratacion", "maquinaria-industrial"],
  "stand-morocco-medical-expo-casablanca": ["congreso-medico", "farmacia"],
  "stand-morocco-textile-expo-casablanca": ["moda-textil"],
  "stand-stitch-tex-casablanca": ["moda-textil", "maquinaria-industrial"],
  "stand-maroc-in-mode-mim-casablanca": ["moda-textil"],
  "stand-ctw-china-trade-week-casablanca": ["multisectorial", "congreso-profesional"],
  "stand-siel-rabat": ["cultura-arte", "congreso-profesional"],
  "stand-visa-for-music-rabat": ["cultura-arte", "congreso-profesional"],
  "stand-forum-etudiant-rabat": ["congreso-profesional"],
  "stand-cimqusef-rabat": ["congreso-profesional"]
};

// Helpers
export const activitiesForFair = (slug) => fairActivities[slug] || [];
export const colorForTag = (tag) => (tagFamilies[fairTags[tag]?.family]?.color) || '#6F757D';
export const labelForTag = (tag, lang) => (fairTags[tag]?.label?.[lang]) || fairTags[tag]?.label?.es || tag;
export const familyLabel = (fam, lang) => (tagFamilies[fam]?.label?.[lang]) || tagFamilies[fam]?.sector || fam;

// Lista de etiquetas en orden de familia (para el índice y los chips agrupados).
export const tagOrder = Object.keys(fairTags).sort((a, b) => {
  const fa = Object.keys(tagFamilies).indexOf(fairTags[a].family);
  const fb = Object.keys(tagFamilies).indexOf(fairTags[b].family);
  return fa - fb;
});

// Índice inverso: etiqueta -> [slugs de feria]. Se construye una vez al cargar el módulo.
const _fairsByTag = (() => {
  const idx = {};
  for (const tag of Object.keys(fairTags)) idx[tag] = [];
  for (const [slug, tags] of Object.entries(fairActivities)) {
    for (const t of tags) (idx[t] || (idx[t] = [])).push(slug);
  }
  return idx;
})();
export const fairsForActivity = (tag) => _fairsByTag[tag] || [];
export const fairCountForActivity = (tag) => (_fairsByTag[tag] || []).length;
