// Sistema de etiquetado de ferias por actividad (Fase 0 — solo datos).
// families: cada familia = un 'sector' de fairsData, con su color (código de colores).
// tags: etiqueta -> { family, label }. (labels en más idiomas se añaden en Fase 1).
// fairActivities: slug de feria -> [etiquetas] (multivalor). Fuente de verdad del etiquetado.
export const tagFamilies = {
  agroalimentario: { sector: "Agroalimentario y Naturaleza", color: '#3A9D4E' },
  industria: { sector: "Industria y Logística", color: '#5B6B7A' },
  salud: { sector: "Salud y Medicina", color: '#E05A5A' },
  tecnologia: { sector: "Tecnología e Innovación", color: '#2F7FD1' },
  comercio: { sector: "Comercio y Packaging", color: '#E8902A' },
  construccion: { sector: "Construcción e Infraestructuras", color: '#A8763E' },
  turismo: { sector: "Turismo y Hostelería", color: '#1AA7A0' },
  transporte: { sector: "Aeronáutica y Transporte", color: '#34508C' },
  enologia: { sector: "Enología y Vinos", color: '#7A2E46' },
  ocio: { sector: "Arte y Ocio", color: '#8E5BB5' },
  belleza: { sector: "Belleza y Estética", color: '#D6589E' },
  multi: { sector: "Multisectorial y Profesional", color: '#6F757D' }
};

export const fairTags = {
  "alimentacion": { family: 'agroalimentario', label: { es: "Alimentación" } },
  "ganaderia": { family: 'agroalimentario', label: { es: "Ganadería" } },
  "agricultura-maquinaria": { family: 'agroalimentario', label: { es: "Agricultura y maquinaria agrícola" } },
  "ecologico": { family: 'agroalimentario', label: { es: "Ecológico y sostenible" } },
  "pesca-mar": { family: 'agroalimentario', label: { es: "Pesca y mar" } },
  "maquinaria-industrial": { family: 'industria', label: { es: "Maquinaria industrial" } },
  "metal-subcontratacion": { family: 'industria', label: { es: "Metal y subcontratación" } },
  "logistica": { family: 'industria', label: { es: "Logística" } },
  "energia": { family: 'industria', label: { es: "Energía" } },
  "dental": { family: 'salud', label: { es: "Dental y ortodoncia" } },
  "optica-oftalmologia": { family: 'salud', label: { es: "Óptica y oftalmología" } },
  "medicina-estetica": { family: 'salud', label: { es: "Medicina estética" } },
  "farmacia": { family: 'salud', label: { es: "Farmacia" } },
  "veterinaria": { family: 'salud', label: { es: "Veterinaria" } },
  "congreso-medico": { family: 'salud', label: { es: "Congreso médico" } },
  "digital-software": { family: 'tecnologia', label: { es: "Tecnología digital y software" } },
  "audiovisual": { family: 'tecnologia', label: { es: "Audiovisual y VFX" } },
  "fotonica": { family: 'tecnologia', label: { es: "Fotónica y optoelectrónica" } },
  "smart-city": { family: 'tecnologia', label: { es: "Smart city" } },
  "packaging": { family: 'comercio', label: { es: "Packaging y envase" } },
  "moda-textil": { family: 'comercio', label: { es: "Moda y textil" } },
  "regalo-decoracion": { family: 'comercio', label: { es: "Regalo y decoración" } },
  "joyeria": { family: 'comercio', label: { es: "Joyería y bisutería" } },
  "construccion": { family: 'construccion', label: { es: "Construcción" } },
  "ventanas-cerramientos": { family: 'construccion', label: { es: "Ventanas y cerramientos" } },
  "puertas": { family: 'construccion', label: { es: "Puertas" } },
  "turismo": { family: 'turismo', label: { es: "Turismo" } },
  "gastronomia-hosteleria": { family: 'turismo', label: { es: "Gastronomía y hostelería" } },
  "automocion": { family: 'transporte', label: { es: "Automoción" } },
  "naval": { family: 'transporte', label: { es: "Naval" } },
  "aeronautica": { family: 'transporte', label: { es: "Aeronáutica" } },
  "transporte": { family: 'transporte', label: { es: "Transporte y logística" } },
  "vino": { family: 'enologia', label: { es: "Vino y enología" } },
  "equipamiento-vino": { family: 'enologia', label: { es: "Equipamiento del vino" } },
  "cultura-arte": { family: 'ocio', label: { es: "Cultura y arte" } },
  "pop-videojuegos": { family: 'ocio', label: { es: "Cultura pop y videojuegos" } },
  "mascotas": { family: 'ocio', label: { es: "Mascotas" } },
  "belleza-peluqueria": { family: 'belleza', label: { es: "Belleza y peluquería" } },
  "estetica": { family: 'belleza', label: { es: "Estética" } },
  "multisectorial": { family: 'multi', label: { es: "Multisectorial" } },
  "congreso-profesional": { family: 'multi', label: { es: "Congreso profesional" } }
};

export const fairActivities = {
  "agroexpo-feval-don-benito": ["agricultura-maquinaria"],
  "feria-de-fp-badajoz": ["multisectorial"],
  "feria-de-los-mayores-de-extremadura-badajoz": ["multisectorial"],
  "fio-monfrague": ["alimentacion"],
  "feria-de-belleza-moda-y-cosmetica-badajoz": ["moda-textil"],
  "vinac-almendralejo": ["vino"],
  "artexania-plasencia": ["cultura-arte"],
  "fenavin-match-ciudad-real": ["vino"],
  "ferduque-ciudad-real": ["vino"],
  "jec-world-paris": ["aeronautica"],
  "logimat-stuttgart": ["logistica"],
  "global-industrie-paris": ["maquinaria-industrial"],
  "ecuextre-badajoz": ["multisectorial"],
  "hannover-messe": ["maquinaria-industrial"],
  "sagalexpo-lisboa": ["multisectorial"],
  "sil-lisboa": ["logistica"],
  "fercam-manzanares-ciudad-real": ["agricultura-maquinaria"],
  "portugal-smart-cities-summit": ["digital-software","smart-city","congreso-profesional"],
  "arcolisboa": ["cultura-arte"],
  "des-malaga": ["digital-software"],
  "cm-malaga": ["multisectorial"],
  "foro-greencities-malaga": ["digital-software","smart-city"],
  "fercatur-ciudad-real": ["multisectorial"],
  "feciex-badajoz": ["multisectorial"],
  "san-diego-comic-con-malaga": ["pop-videojuegos"],
  "expo-agritech-malaga": ["agricultura-maquinaria"],
  "simed-malaga": ["construccion"],
  "fehispor-badajoz": ["multisectorial"],
  "amb-stuttgart": ["maquinaria-industrial"],
  "iberocio-badajoz": ["cultura-arte"],
  "sps-nuremberg": ["maquinaria-industrial"],
  "automatica-munich": ["maquinaria-industrial"],
  "pollutec-lyon": ["energia"],
  "bauma-munich": ["maquinaria-industrial"],
  "fireca-sevilla": ["multisectorial"],
  "conxemar-vigo": ["alimentacion","pesca-mar"],
  "veteco-madrid": ["ventanas-cerramientos"],
  "piscimad-madrid": ["construccion"],
  "greencities-malaga": ["digital-software","smart-city"],
  "iberpet-madrid": ["mascotas"],
  "ht-malaga": ["gastronomia-hosteleria"],
  "eurosatory-paris": ["aeronautica"],
  "empack-madrid": ["packaging"],
  "expoquimia-barcelona": ["packaging"],
  "mwc-barcelona": ["digital-software"],
  "ise-barcelona": ["audiovisual"],
  "alimentaria-barcelona": ["alimentacion"],
  "hispack-barcelona": ["packaging"],
  "hostelco-barcelona": ["gastronomia-hosteleria"],
  "smart-city-expo-world-congress-barcelona": ["digital-software","smart-city","congreso-profesional"],
  "construmat-barcelona": ["construccion"],
  "iot-solutions-world-congress-barcelona": ["digital-software","congreso-profesional"],
  "smart-doors-madrid": ["smart-city","puertas"],
  "equiplast-barcelona": ["packaging"],
  "tis-sevilla": ["digital-software"],
  "autentica-sevilla": ["multisectorial"],
  "esicm-lives-lisboa": ["congreso-medico"],
  "lisbon-food-affair": ["alimentacion"],
  "snackex-lisboa": ["alimentacion"],
  "gse-expo-lisboa": ["aeronautica"],
  "esra-congress-lisboa": ["congreso-medico","congreso-profesional"],
  "world-aviation-festival-lisboa": ["aeronautica"],
  "pegs-europe-lisboa": ["congreso-medico"],
  "btl-lisboa": ["turismo"],
  "smopyc-zaragoza": ["maquinaria-industrial"],
  "fima-zaragoza": ["agricultura-maquinaria"],
  "feria-internacional-ganadera-zafra": ["ganaderia"],
  "web-summit-lisboa": ["digital-software","congreso-profesional"],
  "tektonica-lisboa": ["construccion"],
  "biemh-bilbao": ["maquinaria-industrial"],
  "subcontratacion-bilbao": ["metal-subcontratacion"],
  "addit3d-bilbao": ["metal-subcontratacion"],
  "bedigital-bilbao": ["digital-software"],
  "pumps-valves-bilbao": ["maquinaria-industrial"],
  "maintenance-bilbao": ["maquinaria-industrial"],
  "fruit-attraction-madrid": ["alimentacion"],
  "salon-look-madrid": ["estetica"],
  "madrid-tech-show": ["digital-software"],
  "the-district-madrid": ["construccion"],
  "intergift-madrid": ["regalo-decoracion"],
  "momad-madrid": ["moda-textil"],
  "madridjoya-madrid": ["joyeria"],
  "bisutex-madrid": ["joyeria"],
  "fitur-madrid": ["turismo"],
  "arcomadrid": ["cultura-arte"],
  "salon-gourmets-madrid": ["alimentacion"],
  "rebuild-madrid": ["construccion"],
  "madrid-fusion": ["turismo"],
  "expofranquicia-madrid": ["multisectorial"],
  "concreta-oporto": ["construccion"],
  "expocosmetica-oporto": ["estetica"],
  "empack-oporto": ["packaging"],
  "itf-intertex-oporto": ["maquinaria-industrial"],
  "expomecanica-oporto": ["transporte"],
  "emaf-oporto": ["maquinaria-industrial"],
  "portojoia-oporto": ["joyeria"],
  "decor-hotel-oporto": ["turismo"],
  "expocarne-oporto": ["alimentacion"],
  "cevisama-valencia": ["construccion"],
  "habitat-valencia": ["packaging"],
  "textilhogar-valencia": ["moda-textil"],
  "espacio-cocina-sici-valencia": ["packaging"],
  "fimma-maderalia-valencia": ["maquinaria-industrial"],
  "iberflora-valencia": ["alimentacion"],
  "gastronoma-valencia": ["gastronomia-hosteleria"],
  "eurobrico-valencia": ["packaging"],
  "palma-international-boat-show": ["transporte"],
  "palma-superyacht-village": ["transporte"],
  "baleart-mallorca": ["cultura-arte"],
  "dijous-bo-mallorca": ["multisectorial"],
  "figan-zaragoza": ["alimentacion"],
  "enomaq-zaragoza": ["vino"],
  "oleomaq-zaragoza": ["alimentacion"],
  "tecnovid-zaragoza": ["vino"],
  "navalia-vigo": ["naval"],
  "nortrans-vigo": ["transporte"],
  "moldplas-batalha": ["maquinaria-industrial"],
  "expometal-batalha": ["metal-subcontratacion"],
  "stone-iberica-batalha": ["construccion"],
  "vidrotec-batalha": ["construccion"],
  "decorhotel-batalha": ["turismo"],
  "ovibeja-beja": ["alimentacion"],
  "fatacil-lagoa": ["multisectorial"],
  "faceco-moncarapacho": ["multisectorial"],
  "feira-de-sao-martinho-portimao": ["multisectorial"],
  "feira-daires-viana-do-alentejo": ["multisectorial"],
  "fairway-santiago-de-compostela": ["turismo"],
  "maker-faire-galicia-santiago-de-compostela": ["digital-software"],
  "gedet-santiago-de-compostela": ["congreso-medico"],
  "semergen-santiago-de-compostela": ["medicina-estetica","congreso-profesional"],
  "sesmi-santiago-de-compostela": ["congreso-medico"],
  "forum-gastronomico-a-coruna": ["gastronomia-hosteleria"],
  "mundos-digitales-a-coruna": ["digital-software","audiovisual"],
  "biocultura-a-coruna": ["ecologico"],
  "agraria-valladolid": ["agricultura-maquinaria"],
  "agrovid-valladolid": ["agricultura-maquinaria"],
  "aviforum-valladolid": ["veterinaria"],
  "fimascota-valladolid": ["mascotas"],
  "salamaq-salamanca": ["ganaderia"],
  "salon-automovil-salamanca": ["automocion"],
  "congreso-alineadores-salamanca": ["dental","congreso-profesional"],
  "expodental-madrid": ["dental"],
  "forum-dental-mediterraneo-barcelona": ["dental"],
  "expooptica-madrid": ["optica-oftalmologia"],
  "optom-madrid": ["optica-oftalmologia"],
  "cioc-lisboa": ["optica-oftalmologia"],
  "ciocv-braga": ["optica-oftalmologia"],
  "foyer-health-beauty-lisboa": ["medicina-estetica","congreso-profesional"],
  "seme-medicina-estetica": ["medicina-estetica","estetica","congreso-profesional"],
  "secpre-cirugia-plastica": ["packaging","congreso-medico","congreso-profesional"],
  "spcpre-cirugia-plastica-portugal": ["packaging","congreso-medico","congreso-profesional"],
  "spme-medicina-estetica-portugal": ["medicina-estetica","estetica","congreso-profesional"],
  "seo-oftalmologia": ["optica-oftalmologia","congreso-profesional"],
  "secoir-cirugia-ocular": ["optica-oftalmologia","congreso-profesional"],
  "rno-reunion-nacional-optica": ["optica-oftalmologia","fotonica","congreso-profesional"],
  "optoel-optoelectronica": ["fotonica","congreso-profesional"],
  "set-trasplante": ["congreso-medico","congreso-profesional"]
};

// Helpers
export const activitiesForFair = (slug) => fairActivities[slug] || [];
export const colorForTag = (tag) => (tagFamilies[fairTags[tag]?.family]?.color) || '#6F757D';
