// Sistema de etiquetado de ferias por actividad.
// families: cada familia = un 'sector' de fairsData, con su color (código de colores).
// tags: etiqueta -> { family, label } (label en los 11 idiomas).
// fairActivities: slug de feria -> [etiquetas] (multivalor). Fuente de verdad del etiquetado.
// label: nombre de la familia en los 11 idiomas (cabeceras de subfamilia en el
// índice /actividad y en el asesor Pat). sector = nombre ES (compat interna).
export const tagFamilies = {
  agroalimentario: { sector: "Agroalimentario y Naturaleza", color: '#3A9D4E', label: { es: "Agroalimentario y Naturaleza", pt: "Agroalimentar e Natureza", en: "Agrifood & Nature", de: "Agrar & Natur", fr: "Agroalimentaire et nature", it: "Agroalimentare e natura", nl: "Agrovoeding & natuur", zh: "农业食品与自然", hi: "कृषि-खाद्य एवं प्रकृति", ko: "농식품 및 자연", ja: "農産物・自然" } },
  industria: { sector: "Industria y Logística", color: '#5B6B7A', label: { es: "Industria y Logística", pt: "Indústria e Logística", en: "Industry & Logistics", de: "Industrie & Logistik", fr: "Industrie et logistique", it: "Industria e logistica", nl: "Industrie & logistiek", zh: "工业与物流", hi: "उद्योग एवं लॉजिस्टिक्स", ko: "산업 및 물류", ja: "産業・物流" } },
  salud: { sector: "Salud y Medicina", color: '#E05A5A', label: { es: "Salud y Medicina", pt: "Saúde e Medicina", en: "Health & Medicine", de: "Gesundheit & Medizin", fr: "Santé et médecine", it: "Salute e medicina", nl: "Gezondheid & geneeskunde", zh: "健康与医学", hi: "स्वास्थ्य एवं चिकित्सा", ko: "건강 및 의학", ja: "健康・医療" } },
  tecnologia: { sector: "Tecnología e Innovación", color: '#2F7FD1', label: { es: "Tecnología e Innovación", pt: "Tecnologia e Inovação", en: "Technology & Innovation", de: "Technologie & Innovation", fr: "Technologie et innovation", it: "Tecnologia e innovazione", nl: "Technologie & innovatie", zh: "科技与创新", hi: "तकनीक एवं नवाचार", ko: "기술 및 혁신", ja: "テクノロジー・イノベーション" } },
  comercio: { sector: "Comercio y Packaging", color: '#E8902A', label: { es: "Comercio y Packaging", pt: "Comércio e Packaging", en: "Retail & Packaging", de: "Handel & Verpackung", fr: "Commerce et packaging", it: "Commercio e packaging", nl: "Handel & verpakking", zh: "商贸与包装", hi: "व्यापार एवं पैकेजिंग", ko: "유통 및 패키징", ja: "商業・パッケージ" } },
  construccion: { sector: "Construcción e Infraestructuras", color: '#A8763E', label: { es: "Construcción e Infraestructuras", pt: "Construção e Infraestruturas", en: "Construction & Infrastructure", de: "Bau & Infrastruktur", fr: "Construction et infrastructures", it: "Costruzione e infrastrutture", nl: "Bouw & infrastructuur", zh: "建筑与基础设施", hi: "निर्माण एवं अवसंरचना", ko: "건설 및 인프라", ja: "建設・インフラ" } },
  turismo: { sector: "Turismo y Hostelería", color: '#1AA7A0', label: { es: "Turismo y Hostelería", pt: "Turismo e Hotelaria", en: "Tourism & Hospitality", de: "Tourismus & Gastgewerbe", fr: "Tourisme et hôtellerie", it: "Turismo e ospitalità", nl: "Toerisme & horeca", zh: "旅游与酒店", hi: "पर्यटन एवं आतिथ्य", ko: "관광 및 호스피탈리티", ja: "観光・ホスピタリティ" } },
  transporte: { sector: "Aeronáutica y Transporte", color: '#34508C', label: { es: "Aeronáutica y Transporte", pt: "Aeronáutica e Transporte", en: "Aerospace & Transport", de: "Luftfahrt & Transport", fr: "Aéronautique et transport", it: "Aeronautica e trasporti", nl: "Luchtvaart & transport", zh: "航空与交通", hi: "विमानन एवं परिवहन", ko: "항공 및 운송", ja: "航空・輸送" } },
  enologia: { sector: "Enología y Vinos", color: '#7A2E46', label: { es: "Enología y Vinos", pt: "Enologia e Vinhos", en: "Wine & Oenology", de: "Wein & Önologie", fr: "Œnologie et vins", it: "Enologia e vini", nl: "Wijn & oenologie", zh: "葡萄酒与酿酒", hi: "वाइन एवं एनोलॉजी", ko: "와인 및 양조", ja: "ワイン・醸造" } },
  ocio: { sector: "Arte y Ocio", color: '#8E5BB5', label: { es: "Arte y Ocio", pt: "Arte e Lazer", en: "Art & Leisure", de: "Kunst & Freizeit", fr: "Art et loisirs", it: "Arte e tempo libero", nl: "Kunst & vrije tijd", zh: "艺术与休闲", hi: "कला एवं मनोरंजन", ko: "예술 및 여가", ja: "アート・レジャー" } },
  belleza: { sector: "Belleza y Estética", color: '#D6589E', label: { es: "Belleza y Estética", pt: "Beleza e Estética", en: "Beauty & Aesthetics", de: "Schönheit & Ästhetik", fr: "Beauté et esthétique", it: "Bellezza ed estetica", nl: "Schoonheid & esthetiek", zh: "美容与美学", hi: "सौंदर्य एवं एस्थेटिक्स", ko: "뷰티 및 에스테틱", ja: "ビューティー・エステ" } },
  multi: { sector: "Multisectorial y Profesional", color: '#6F757D', label: { es: "Multisectorial y Profesional", pt: "Multissetorial e Profissional", en: "Multi-sector & Professional", de: "Multisektoral & Professionell", fr: "Multisectoriel et professionnel", it: "Multisettoriale e professionale", nl: "Multisectoraal & professioneel", zh: "综合与专业", hi: "बहु-क्षेत्रीय एवं पेशेवर", ko: "다분야 및 전문", ja: "総合・専門" } }
};

export const fairTags = {
  "alimentacion": { family: "agroalimentario", label: { es: "Alimentación", pt: "Alimentação", en: "Food & beverage", de: "Lebensmittel", fr: "Alimentation", it: "Alimentare", nl: "Voeding", zh: "食品", hi: "खाद्य एवं पेय पदार्थ", ko: "식품", ja: "食品" } },
  "ganaderia": { family: "agroalimentario", label: { es: "Ganadería", pt: "Pecuária", en: "Livestock", de: "Viehwirtschaft", fr: "Élevage", it: "Zootecnia", nl: "Veeteelt", zh: "畜牧业", hi: "पशुपालन", ko: "축산", ja: "畜産" } },
  "agricultura-maquinaria": { family: "agroalimentario", label: { es: "Agricultura y maquinaria agrícola", pt: "Agricultura e maquinaria agrícola", en: "Agriculture & farm machinery", de: "Landwirtschaft und Landmaschinen", fr: "Agriculture et machinisme agricole", it: "Agricoltura e macchine agricole", nl: "Landbouw en landbouwmachines", zh: "农业与农业机械", hi: "कृषि एवं कृषि मशीनरी", ko: "농업 및 농기계", ja: "農業・農業機械" } },
  "ecologico": { family: "agroalimentario", label: { es: "Ecológico y sostenible", pt: "Ecológico e sustentável", en: "Organic & sustainable", de: "Bio und Nachhaltigkeit", fr: "Bio et développement durable", it: "Biologico e sostenibile", nl: "Biologisch en duurzaam", zh: "有机与可持续", hi: "जैविक एवं टिकाऊ", ko: "친환경 및 지속가능", ja: "オーガニック・サステナブル" } },
  "pesca-mar": { family: "agroalimentario", label: { es: "Pesca y mar", pt: "Pesca e mar", en: "Fishing & seafood", de: "Fischerei und Meer", fr: "Pêche et produits de la mer", it: "Pesca e prodotti del mare", nl: "Visserij en zee", zh: "渔业与海洋", hi: "मत्स्य पालन एवं समुद्री उत्पाद", ko: "수산 및 해양", ja: "水産・海洋" } },
  "maquinaria-industrial": { family: "industria", label: { es: "Maquinaria industrial", pt: "Maquinaria industrial", en: "Industrial machinery", de: "Industriemaschinen", fr: "Machines industrielles", it: "Macchine industriali", nl: "Industriële machines", zh: "工业机械", hi: "औद्योगिक मशीनरी", ko: "산업 기계", ja: "産業機械" } },
  "metal-subcontratacion": { family: "industria", label: { es: "Metal y subcontratación", pt: "Metalomecânica e subcontratação", en: "Metalworking & subcontracting", de: "Metall und Zulieferindustrie", fr: "Métal et sous-traitance", it: "Metallo e subfornitura", nl: "Metaal en toelevering", zh: "金属与工业外包", hi: "धातु एवं उप-अनुबंध", ko: "금속 및 임가공", ja: "金属・受託製造" } },
  "logistica": { family: "industria", label: { es: "Logística", pt: "Logística", en: "Logistics", de: "Logistik", fr: "Logistique", it: "Logistica", nl: "Logistiek", zh: "物流", hi: "लॉजिस्टिक्स", ko: "물류", ja: "物流" } },
  "energia": { family: "industria", label: { es: "Energía", pt: "Energia", en: "Energy", de: "Energie", fr: "Énergie", it: "Energia", nl: "Energie", zh: "能源", hi: "ऊर्जा", ko: "에너지", ja: "エネルギー" } },
  "dental": { family: "salud", label: { es: "Dental y ortodoncia", pt: "Dentária e ortodontia", en: "Dental & orthodontics", de: "Dental und Kieferorthopädie", fr: "Dentaire et orthodontie", it: "Dentale e ortodonzia", nl: "Tandheelkunde en orthodontie", zh: "牙科与正畸", hi: "डेंटल एवं ऑर्थोडॉन्टिक्स", ko: "치과 및 교정", ja: "歯科・矯正歯科" } },
  "optica-oftalmologia": { family: "salud", label: { es: "Óptica y oftalmología", pt: "Ótica e oftalmologia", en: "Optics & ophthalmology", de: "Optik und Augenheilkunde", fr: "Optique et ophtalmologie", it: "Ottica e oftalmologia", nl: "Optiek en oogheelkunde", zh: "光学与眼科", hi: "ऑप्टिक्स एवं नेत्र विज्ञान", ko: "안경 및 안과", ja: "眼鏡・眼科" } },
  "medicina-estetica": { family: "salud", label: { es: "Medicina estética", pt: "Medicina estética", en: "Aesthetic medicine", de: "Ästhetische Medizin", fr: "Médecine esthétique", it: "Medicina estetica", nl: "Esthetische geneeskunde", zh: "医学美容", hi: "सौंदर्य चिकित्सा", ko: "미용 의학", ja: "美容医療" } },
  "farmacia": { family: "salud", label: { es: "Farmacia", pt: "Farmácia", en: "Pharmaceuticals", de: "Pharmazie", fr: "Pharmacie", it: "Farmacia", nl: "Farmacie", zh: "制药", hi: "फार्मास्युटिकल", ko: "제약", ja: "製薬" } },
  "veterinaria": { family: "salud", label: { es: "Veterinaria", pt: "Veterinária", en: "Veterinary", de: "Veterinärmedizin", fr: "Vétérinaire", it: "Veterinaria", nl: "Diergeneeskunde", zh: "兽医", hi: "पशु चिकित्सा", ko: "수의", ja: "動物医療" } },
  "congreso-medico": { family: "salud", label: { es: "Congreso médico", pt: "Congresso médico", en: "Medical congress", de: "Medizinkongress", fr: "Congrès médical", it: "Congresso medico", nl: "Medisch congres", zh: "医学大会", hi: "चिकित्सा सम्मेलन", ko: "의학 학술대회", ja: "医学会議" } },
  "digital-software": { family: "tecnologia", label: { es: "Tecnología digital y software", pt: "Tecnologia digital e software", en: "Digital tech & software", de: "Digitaltechnik und Software", fr: "Technologies numériques et logiciels", it: "Tecnologia digitale e software", nl: "Digitale technologie en software", zh: "数字技术与软件", hi: "डिजिटल तकनीक एवं सॉफ्टवेयर", ko: "디지털 기술 및 소프트웨어", ja: "デジタル技術・ソフトウェア" } },
  "audiovisual": { family: "tecnologia", label: { es: "Audiovisual y VFX", pt: "Audiovisual e VFX", en: "Audiovisual & VFX", de: "Audiovisuelles und VFX", fr: "Audiovisuel et VFX", it: "Audiovisivo e VFX", nl: "Audiovisueel en VFX", zh: "视听与视觉特效", hi: "ऑडियोविज़ुअल एवं VFX", ko: "영상 및 VFX", ja: "映像・VFX" } },
  "fotonica": { family: "tecnologia", label: { es: "Fotónica y optoelectrónica", pt: "Fotónica e optoeletrónica", en: "Photonics & optoelectronics", de: "Photonik und Optoelektronik", fr: "Photonique et optoélectronique", it: "Fotonica e optoelettronica", nl: "Fotonica en opto-elektronica", zh: "光子学与光电子", hi: "फोटोनिक्स एवं ऑप्टोइलेक्ट्रॉनिक्स", ko: "포토닉스 및 광전자", ja: "フォトニクス・オプトエレクトロニクス" } },
  "smart-city": { family: "tecnologia", label: { es: "Smart city", pt: "Smart city", en: "Smart city", de: "Smart City", fr: "Smart city", it: "Smart city", nl: "Smart city", zh: "智慧城市", hi: "स्मार्ट सिटी", ko: "스마트 시티", ja: "スマートシティ" } },
  "packaging": { family: "comercio", label: { es: "Packaging y envase", pt: "Packaging e embalagem", en: "Packaging", de: "Verpackung", fr: "Packaging et emballage", it: "Packaging e imballaggio", nl: "Verpakking", zh: "包装与封装", hi: "पैकेजिंग एवं पैकिंग", ko: "패키징 및 포장", ja: "パッケージ・包装" } },
  "moda-textil": { family: "comercio", label: { es: "Moda y textil", pt: "Moda e têxtil", en: "Fashion & textiles", de: "Mode und Textil", fr: "Mode et textile", it: "Moda e tessile", nl: "Mode en textiel", zh: "时尚与纺织", hi: "फैशन एवं वस्त्र", ko: "패션 및 섬유", ja: "ファッション・繊維" } },
  "regalo-decoracion": { family: "comercio", label: { es: "Regalo y decoración", pt: "Presentes e decoração", en: "Gifts & home décor", de: "Geschenkartikel und Dekoration", fr: "Cadeau et décoration", it: "Regalo e decorazione", nl: "Cadeau en decoratie", zh: "礼品与装饰", hi: "उपहार एवं सजावट", ko: "선물 및 인테리어", ja: "ギフト・インテリア" } },
  "joyeria": { family: "comercio", label: { es: "Joyería y bisutería", pt: "Joalharia e bijutaria", en: "Jewellery & costume jewellery", de: "Schmuck und Modeschmuck", fr: "Bijouterie et joaillerie", it: "Gioielleria e bigiotteria", nl: "Juwelen en sieraden", zh: "珠宝与饰品", hi: "आभूषण एवं इमिटेशन ज्वेलरी", ko: "주얼리 및 액세서리", ja: "ジュエリー・アクセサリー" } },
  "construccion": { family: "construccion", label: { es: "Construcción", pt: "Construção", en: "Construction", de: "Bauwesen", fr: "Construction", it: "Edilizia", nl: "Bouw", zh: "建筑", hi: "निर्माण", ko: "건설", ja: "建設" } },
  "ventanas-cerramientos": { family: "construccion", label: { es: "Ventanas y cerramientos", pt: "Janelas e caixilharia", en: "Windows & façades", de: "Fenster und Fassaden", fr: "Fenêtres et menuiseries", it: "Serramenti e infissi", nl: "Ramen en gevelsluitingen", zh: "门窗与幕墙", hi: "खिड़कियां एवं क्लोज़र", ko: "창호 및 외장", ja: "窓・建具" } },
  "puertas": { family: "construccion", label: { es: "Puertas", pt: "Portas", en: "Doors", de: "Türen", fr: "Portes", it: "Porte", nl: "Deuren", zh: "门业", hi: "दरवाज़े", ko: "도어", ja: "ドア" } },
  "turismo": { family: "turismo", label: { es: "Turismo", pt: "Turismo", en: "Tourism", de: "Tourismus", fr: "Tourisme", it: "Turismo", nl: "Toerisme", zh: "旅游", hi: "पर्यटन", ko: "관광", ja: "観光" } },
  "gastronomia-hosteleria": { family: "turismo", label: { es: "Gastronomía y hostelería", pt: "Gastronomia e hotelaria", en: "Gastronomy & hospitality", de: "Gastronomie und Hotellerie", fr: "Gastronomie et hôtellerie-restauration", it: "Gastronomia e ristorazione", nl: "Gastronomie en horeca", zh: "餐饮与酒店", hi: "गैस्ट्रोनॉमी एवं आतिथ्य", ko: "외식 및 호텔", ja: "美食・外食" } },
  "automocion": { family: "transporte", label: { es: "Automoción", pt: "Automóvel", en: "Automotive", de: "Automobil", fr: "Automobile", it: "Automotive", nl: "Automotive", zh: "汽车", hi: "ऑटोमोटिव", ko: "자동차", ja: "自動車" } },
  "naval": { family: "transporte", label: { es: "Naval", pt: "Naval", en: "Naval & shipbuilding", de: "Schiffbau", fr: "Naval", it: "Navale", nl: "Scheepvaart", zh: "船舶", hi: "जहाज़ निर्माण", ko: "조선", ja: "造船" } },
  "aeronautica": { family: "transporte", label: { es: "Aeronáutica", pt: "Aeronáutica", en: "Aerospace", de: "Luft- und Raumfahrt", fr: "Aéronautique", it: "Aeronautica", nl: "Luchtvaart", zh: "航空", hi: "एयरोनॉटिक्स", ko: "항공우주", ja: "航空" } },
  "transporte": { family: "transporte", label: { es: "Transporte y logística", pt: "Transporte e logística", en: "Transport & logistics", de: "Transport und Logistik", fr: "Transport et logistique", it: "Trasporti e logistica", nl: "Transport en logistiek", zh: "运输与物流", hi: "परिवहन एवं लॉजिस्टिक्स", ko: "운송 및 물류", ja: "運輸・物流" } },
  "movilidad": { family: "transporte", label: { es: "Movilidad, ITS y tráfico", pt: "Mobilidade, ITS e tráfego", en: "Mobility, ITS & traffic", de: "Mobilität, ITS & Verkehr", fr: "Mobilité, ITS et trafic", it: "Mobilità, ITS e traffico", nl: "Mobiliteit, ITS & verkeer", zh: "出行、ITS 与交通", hi: "गतिशीलता, ITS एवं यातायात", ko: "모빌리티, ITS 및 교통", ja: "モビリティ・ITS・交通" } },
  "vino": { family: "enologia", label: { es: "Vino y enología", pt: "Vinho e enologia", en: "Wine & oenology", de: "Wein und Önologie", fr: "Vin et œnologie", it: "Vino ed enologia", nl: "Wijn en oenologie", zh: "葡萄酒与酿酒", hi: "वाइन एवं एनोलॉजी", ko: "와인 및 양조", ja: "ワイン・醸造" } },
  "equipamiento-vino": { family: "enologia", label: { es: "Equipamiento del vino", pt: "Equipamento vínico", en: "Winemaking equipment", de: "Weinkellereitechnik", fr: "Équipement vinicole", it: "Attrezzature per il vino", nl: "Wijnuitrusting", zh: "葡萄酒酿造设备", hi: "वाइन उपकरण", ko: "와인 설비", ja: "ワイン関連設備" } },
  "cultura-arte": { family: "ocio", label: { es: "Cultura y arte", pt: "Cultura e arte", en: "Culture & art", de: "Kultur und Kunst", fr: "Culture et art", it: "Cultura e arte", nl: "Cultuur en kunst", zh: "文化与艺术", hi: "संस्कृति एवं कला", ko: "문화 및 예술", ja: "文化・芸術" } },
  "pop-videojuegos": { family: "ocio", label: { es: "Cultura pop y videojuegos", pt: "Cultura pop e videojogos", en: "Pop culture & video games", de: "Popkultur und Videospiele", fr: "Culture pop et jeux vidéo", it: "Cultura pop e videogiochi", nl: "Popcultuur en games", zh: "流行文化与电子游戏", hi: "पॉप संस्कृति एवं वीडियो गेम", ko: "대중문화 및 게임", ja: "ポップカルチャー・ゲーム" } },
  "mascotas": { family: "ocio", label: { es: "Mascotas", pt: "Animais de estimação", en: "Pets", de: "Heimtiere", fr: "Animaux de compagnie", it: "Animali da compagnia", nl: "Huisdieren", zh: "宠物", hi: "पालतू पशु", ko: "반려동물", ja: "ペット" } },
  "belleza-peluqueria": { family: "belleza", label: { es: "Belleza y peluquería", pt: "Beleza e cabeleireiro", en: "Beauty & hairdressing", de: "Beauty und Friseurhandwerk", fr: "Beauté et coiffure", it: "Bellezza e acconciatura", nl: "Schoonheid en kappers", zh: "美容与美发", hi: "सौंदर्य एवं हेयरड्रेसिंग", ko: "뷰티 및 헤어", ja: "美容・ヘアサロン" } },
  "estetica": { family: "belleza", label: { es: "Estética", pt: "Estética", en: "Aesthetics", de: "Kosmetik", fr: "Esthétique", it: "Estetica", nl: "Esthetiek", zh: "美容护理", hi: "एस्थेटिक्स", ko: "에스테틱", ja: "エステティック" } },
  "multisectorial": { family: "multi", label: { es: "Multisectorial", pt: "Multissetorial", en: "Multi-sector", de: "Branchenübergreifend", fr: "Multisectoriel", it: "Multisettoriale", nl: "Multisectoraal", zh: "综合行业", hi: "बहु-क्षेत्रीय", ko: "종합 산업", ja: "総合展示会" } },
  "congreso-profesional": { family: "multi", label: { es: "Congreso profesional", pt: "Congresso profissional", en: "Professional congress", de: "Fachkongress", fr: "Congrès professionnel", it: "Congresso professionale", nl: "Vakcongres", zh: "专业大会", hi: "पेशेवर सम्मेलन", ko: "전문 학술대회", ja: "専門学会・会議" } },
};
export const fairActivities = {
  "artesantander": ["cultura-arte"],
  "biocantabria-santander": ["ecologico", "alimentacion"],
  "feria-apicola-cantabria-torrelavega": ["ganaderia", "alimentacion"],
  "feria-concesionarios-torrelavega": ["automocion"],
  "fidma-gijon": ["multisectorial"],
  "agropec-gijon": ["ganaderia", "agricultura-maquinaria"],
  "salon-competicion-asturias-gijon": ["automocion"],
  "asturforesta-tineo": ["agricultura-maquinaria", "ecologico"],
  "feria-muestras-tineo": ["multisectorial"],
  "agroalimentaria-vegadeo": ["alimentacion", "ecologico"],
  "cargo-freight-portugal-summit": ["transporte"],
  "techlogistics-lisboa": ["transporte"],
  "scm-conference": ["transporte"],
  "airspace-world-lisboa": ["aeronautica"],
  "expomadeira": ["multisectorial"],
  "feira-agropecuaria-madeira": ["agricultura-maquinaria", "ganaderia"],
  "feira-emprego-formacao-empreendedorismo-madeira": ["multisectorial"],
  "feira-empreendedorismo-madeira": ["digital-software"],
  "festa-vinho-madeira": ["vino"],
  "cider-fest-madeira": ["gastronomia-hosteleria"],
  "feaga-fuerteventura": ["agricultura-maquinaria", "ganaderia"],
  "gastrocanarias-tenerife": ["gastronomia-hosteleria"],
  "gran-canaria-me-gusta": ["alimentacion", "gastronomia-hosteleria"],
  "fimar-las-palmas": ["pesca-mar", "naval"],
  "salon-atlantico-logistica-transporte": ["logistica", "transporte"],
  "moda-tenerife": ["moda-textil"],
  "expodeca": ["regalo-decoracion"],
  "feboda": ["multisectorial"],
  "canarias-destino-startup": ["digital-software"],
  "feria-empresarial-norte-gran-canaria": ["multisectorial"],
  "futuralia-lisboa": ["multisectorial"],
  "seafood-expo-global-barcelona": ["pesca-mar", "alimentacion"],
  "sil-barcelona": ["logistica"],
  "automobile-barcelona": ["automocion"],
  "piscina-wellness-barcelona": ["construccion", "turismo"],
  "municipalia-lleida": ["construccion", "smart-city"],
  "fira-sant-miquel-lleida": ["agricultura-maquinaria"],
  "forum-gastronomic-girona": ["gastronomia-hosteleria", "alimentacion"],
  "mindtech-vigo": ["metal-subcontratacion"],
  "galicia-escena-pro-santiago-de-compostela": ["cultura-arte"],
  "semana-verde-galicia-silleda": ["multisectorial", "ganaderia"],
  "turexpo-galicia-silleda": ["turismo"],
  "xantar-ourense": ["gastronomia-hosteleria"],
  "termatalia-ourense": ["turismo"],
  "galiforest-boqueixon": ["agricultura-maquinaria", "ecologico"],
  "infoagro-exhibition-aguadulce": ["agricultura-maquinaria", "ecologico"],
  "expolevante-el-ejido": ["agricultura-maquinaria"],
  "sun-blue-congress-almeria": ["turismo", "ecologico"],
  "expoliva-jaen": ["alimentacion", "agricultura-maquinaria"],
  "ibercaza-jaen": ["ecologico", "pesca-mar"],
  "feria-de-los-pueblos-jaen": ["multisectorial", "turismo"],
  "congreso-internacional-frutos-rojos-huelva": ["alimentacion", "agricultura-maquinaria"],
  "feria-jamon-cerdo-iberico-aracena": ["alimentacion", "ganaderia"],
  "feria-gamba-chirla-boqueron-punta-umbria": ["pesca-mar", "alimentacion"],
  "intercaza-cordoba": ["ecologico", "pesca-mar"],
  "feria-agroganadera-pedroches-pozoblanco": ["ganaderia", "agricultura-maquinaria"],
  "feria-jamon-bellota-dop-pedroches-villanueva-cordoba": ["alimentacion", "ganaderia"],
  "feria-general-muestras-armilla": ["multisectorial"],
  "feria-de-la-ciencia-granada": ["digital-software"],
  "concab-granada": ["ganaderia"],
  "blue-zone-forum-navalia-meeting-cadiz": ["naval", "energia"],
  "feria-del-caballo-jerez": ["turismo"],
  "fegasur-jerez": ["ganaderia"],
  "futurmoda-elche": ["moda-textil", "maquinaria-industrial"],
  "firauto-elche": ["automocion"],
  "alicante-gastronomica": ["gastronomia-hosteleria"],
  "fame-innowa-torre-pacheco": ["agricultura-maquinaria", "ganaderia"],
  "equimur-torre-pacheco": ["ganaderia"],
  "hortifruit-torre-pacheco": ["agricultura-maquinaria", "alimentacion"],
  "fecons-torre-pacheco": ["construccion"],
  "agroexpo-feval-don-benito": ["agricultura-maquinaria"],
  "feria-de-fp-badajoz": ["multisectorial"],
  "feria-de-los-mayores-de-extremadura-badajoz": ["multisectorial"],
  "fio-monfrague": ["alimentacion"],
  "feria-de-belleza-moda-y-cosmetica-badajoz": ["belleza-peluqueria","estetica","moda-textil"],
  "vinac-almendralejo": ["vino","equipamiento-vino"],
  "artexania-plasencia": ["cultura-arte"],
  "fenavin-match-ciudad-real": ["vino"],
  "ferduque-ciudad-real": ["ganaderia", "agricultura-maquinaria"],
  "intur-valladolid": ["turismo"],
  "fromago-cheese-experience-zamora": ["alimentacion"],
  "expovicaman-albacete": ["agricultura-maquinaria", "ganaderia"],
  "farcama-toledo": ["cultura-arte"],
  "feria-artesania-valladolid": ["cultura-arte"],
  "feria-vino-do-bierzo-cacabelos": ["vino"],
  "feria-churra-palencia": ["ganaderia"],
  "jec-world-paris": ["aeronautica"],
  "logimat-stuttgart": ["logistica"],
  "global-industrie-paris": ["maquinaria-industrial"],
  "ecuextre-badajoz": ["multisectorial"],
  "hannover-messe": ["maquinaria-industrial"],
  "sagalexpo-lisboa": ["multisectorial"],
  "sil-lisboa": ["logistica"],
  "fercam-manzanares-ciudad-real": ["agricultura-maquinaria"],
  "portugal-smart-cities-summit": ["digital-software","smart-city","congreso-profesional","movilidad","naval"],
  "arcolisboa": ["cultura-arte"],
  "des-malaga": ["digital-software"],
  "cm-malaga": ["multisectorial"],
  "foro-greencities-malaga": ["digital-software","smart-city"],
  "fercatur-ciudad-real": ["multisectorial"],
  "feciex-badajoz": ["multisectorial"],
  "san-diego-comic-con-malaga": ["pop-videojuegos"],
  "expo-agritech-malaga": ["agricultura-maquinaria"],
  "simed-malaga": ["construccion"],
  "fehispor-badajoz": ["multisectorial"],
  "amb-stuttgart": ["maquinaria-industrial"],
  "iberocio-badajoz": ["cultura-arte"],
  "sps-nuremberg": ["maquinaria-industrial"],
  "automatica-munich": ["maquinaria-industrial"],
  "pollutec-lyon": ["energia"],
  "bauma-munich": ["maquinaria-industrial"],
  "fireca-sevilla": ["multisectorial"],
  "conxemar-vigo": ["alimentacion","pesca-mar"],
  "veteco-madrid": ["ventanas-cerramientos"],
  "piscimad-madrid": ["construccion"],
  "greencities-malaga": ["digital-software","smart-city"],
  "iberpet-madrid": ["mascotas"],
  "ht-malaga": ["gastronomia-hosteleria"],
  "eurosatory-paris": ["aeronautica"],
  "empack-madrid": ["packaging"],
  "expoquimia-barcelona": ["packaging"],
  "mwc-barcelona": ["digital-software"],
  "ise-barcelona": ["audiovisual"],
  "alimentaria-barcelona": ["alimentacion"],
  "hispack-barcelona": ["packaging"],
  "hostelco-barcelona": ["gastronomia-hosteleria"],
  "smart-city-expo-world-congress-barcelona": ["digital-software","smart-city","congreso-profesional","movilidad"],
  "construmat-barcelona": ["construccion"],
  "iot-solutions-world-congress-barcelona": ["digital-software","congreso-profesional"],
  "smart-doors-madrid": ["smart-city","puertas"],
  "equiplast-barcelona": ["packaging"],
  "tis-sevilla": ["digital-software"],
  "autentica-sevilla": ["multisectorial"],
  "esicm-lives-lisboa": ["congreso-medico"],
  "lisbon-food-affair": ["alimentacion"],
  "snackex-lisboa": ["alimentacion"],
  "gse-expo-lisboa": ["aeronautica"],
  "esra-congress-lisboa": ["congreso-medico","congreso-profesional"],
  "world-aviation-festival-lisboa": ["aeronautica"],
  "pegs-europe-lisboa": ["congreso-medico"],
  "btl-lisboa": ["turismo"],
  "smopyc-zaragoza": ["maquinaria-industrial"],
  "fima-zaragoza": ["agricultura-maquinaria"],
  "feria-internacional-ganadera-zafra": ["ganaderia","multisectorial","agricultura-maquinaria"],
  "feria-internacional-ganadera-trujillo": ["ganaderia","multisectorial","agricultura-maquinaria"],
  "feria-nacional-queso-trujillo": ["alimentacion","gastronomia-hosteleria"],
  "agroexpo-don-benito": ["agricultura-maquinaria","ganaderia","multisectorial"],
  "web-summit-lisboa": ["digital-software","congreso-profesional"],
  "tektonica-lisboa": ["construccion"],
  "biemh-bilbao": ["maquinaria-industrial"],
  "subcontratacion-bilbao": ["metal-subcontratacion"],
  "addit3d-bilbao": ["metal-subcontratacion"],
  "bedigital-bilbao": ["digital-software"],
  "pumps-valves-bilbao": ["maquinaria-industrial"],
  "maintenance-bilbao": ["maquinaria-industrial"],
  "fruit-attraction-madrid": ["alimentacion"],
  "salon-look-madrid": ["estetica","belleza-peluqueria"],
  "cosmobeauty-barcelona": ["belleza-peluqueria","estetica","medicina-estetica"],
  "beauty-forum-valencia": ["estetica","belleza-peluqueria"],
  "expomedes-madrid": ["medicina-estetica","estetica"],
  "in-beauty-lisboa": ["belleza-peluqueria","estetica"],
  "madrid-tech-show": ["digital-software"],
  "the-district-madrid": ["construccion"],
  "intergift-madrid": ["regalo-decoracion"],
  "momad-madrid": ["moda-textil"],
  "madridjoya-madrid": ["joyeria"],
  "bisutex-madrid": ["joyeria"],
  "fitur-madrid": ["turismo"],
  "arcomadrid": ["cultura-arte"],
  "salon-gourmets-madrid": ["alimentacion","gastronomia-hosteleria","vino"],
  "rebuild-madrid": ["construccion"],
  "madrid-fusion": ["turismo"],
  "expofranquicia-madrid": ["multisectorial"],
  "concreta-oporto": ["construccion"],
  "expocosmetica-oporto": ["belleza-peluqueria","estetica"],
  "empack-oporto": ["packaging", "transporte"],
  "itf-intertex-oporto": ["maquinaria-industrial"],
  "expomecanica-oporto": ["transporte"],
  "emaf-oporto": ["maquinaria-industrial"],
  "portojoia-oporto": ["joyeria"],
  "decor-hotel-oporto": ["turismo"],
  "expocarne-oporto": ["alimentacion"],
  "cevisama-valencia": ["construccion"],
  "habitat-valencia": ["packaging"],
  "textilhogar-valencia": ["moda-textil"],
  "espacio-cocina-sici-valencia": ["packaging"],
  "fimma-maderalia-valencia": ["maquinaria-industrial"],
  "iberflora-valencia": ["alimentacion"],
  "gastronoma-valencia": ["gastronomia-hosteleria"],
  "eurobrico-valencia": ["packaging"],
  "palma-international-boat-show": ["transporte"],
  "palma-superyacht-village": ["transporte"],
  "baleart-mallorca": ["cultura-arte"],
  "dijous-bo-mallorca": ["multisectorial"],
  "figan-zaragoza": ["alimentacion"],
  "enomaq-zaragoza": ["vino","equipamiento-vino"],
  "oleomaq-zaragoza": ["alimentacion"],
  "tecnovid-zaragoza": ["vino","equipamiento-vino"],
  "navalia-vigo": ["naval"],
  "world-maritime-week-bilbao": ["naval","energia"],
  "marine-energy-week-bilbao": ["naval","energia"],
  "blue-zone-forum": ["naval"],
  "sea-portugal": ["naval"],
  "feira-sao-mateus-elvas": ["multisectorial","gastronomia-hosteleria"],
  "feira-nacional-agricultura-santarem": ["agricultura-maquinaria","ganaderia","alimentacion"],
  "fersant-santarem": ["multisectorial"],
  "agroglobal-santarem": ["agricultura-maquinaria"],
  "lusoflora-santarem": ["agricultura-maquinaria"],
  "nortrans-vigo": ["transporte"],
  "moldplas-batalha": ["maquinaria-industrial"],
  "expometal-batalha": ["metal-subcontratacion"],
  "stone-iberica-batalha": ["construccion"],
  "vidrotec-batalha": ["construccion"],
  "decorhotel-batalha": ["turismo"],
  "ovibeja-beja": ["alimentacion"],
  "fatacil-lagoa": ["multisectorial"],
  "faceco-moncarapacho": ["multisectorial"],
  "feira-de-sao-martinho-portimao": ["multisectorial"],
  "feira-daires-viana-do-alentejo": ["multisectorial"],
  "fairway-santiago-de-compostela": ["turismo"],
  "maker-faire-galicia-santiago-de-compostela": ["digital-software"],
  "gedet-santiago-de-compostela": ["congreso-medico"],
  "semergen-santiago-de-compostela": ["medicina-estetica","congreso-profesional"],
  "sesmi-santiago-de-compostela": ["congreso-medico"],
  "forum-gastronomico-a-coruna": ["gastronomia-hosteleria"],
  "mundos-digitales-a-coruna": ["digital-software","audiovisual"],
  "biocultura-a-coruna": ["ecologico"],
  "agraria-valladolid": ["agricultura-maquinaria"],
  "agrovid-valladolid": ["agricultura-maquinaria"],
  "aviforum-valladolid": ["veterinaria"],
  "fimascota-valladolid": ["mascotas"],
  "salamaq-salamanca": ["ganaderia"],
  "salon-automovil-salamanca": ["automocion"],
  "congreso-alineadores-salamanca": ["dental","congreso-profesional"],
  "expodental-madrid": ["dental"],
  "forum-dental-mediterraneo-barcelona": ["dental"],
  "expooptica-madrid": ["optica-oftalmologia"],
  "optom-madrid": ["optica-oftalmologia"],
  "cioc-lisboa": ["optica-oftalmologia"],
  "ciocv-braga": ["optica-oftalmologia"],
  "foyer-health-beauty-lisboa": ["medicina-estetica","congreso-profesional"],
  "seme-medicina-estetica": ["medicina-estetica","estetica","congreso-profesional"],
  "secpre-cirugia-plastica": ["medicina-estetica","congreso-medico","congreso-profesional"],
  "spcpre-cirugia-plastica-portugal": ["medicina-estetica","congreso-medico","congreso-profesional"],
  "spme-medicina-estetica-portugal": ["medicina-estetica","estetica","congreso-profesional"],
  "seo-oftalmologia": ["optica-oftalmologia","congreso-profesional"],
  "infarma": ["farmacia"],
  "farmaforum-madrid": ["farmacia"],
  "congreso-farmaceuticos-comunitarios": ["farmacia","congreso-profesional"],
  "congreso-sefh-farmacia-hospitalaria": ["farmacia","congreso-medico","congreso-profesional"],
  "secoir-cirugia-ocular": ["optica-oftalmologia","congreso-profesional"],
  "rno-reunion-nacional-optica": ["optica-oftalmologia","fotonica","congreso-profesional"],
  "optoel-optoelectronica": ["fotonica","congreso-profesional"],
  "set-trasplante": ["congreso-medico","congreso-profesional"],
  "salon-automovil-merida": ["automocion"],
  "feria-bodas-hogar-merida": ["regalo-decoracion"],
  "coleccionismo-emerita-augusta-merida": ["cultura-arte"],
  "feturex-merida": ["turismo"],
  "salon-gas-renovable-valladolid": ["energia"],
  "genera-madrid": ["energia"],
  "solar-storage-live-espana-valencia": ["energia"],
  "lisbon-energy-summit-lisboa": ["energia","congreso-profesional"],
  "re-plus-portugal-oporto": ["energia","congreso-profesional"],
  "eletrica-oporto": ["energia"],
  "enerh2o-oporto": ["energia"],
  "essencia-do-vinho-porto": ["vino"],
  "simplesmente-vinho-porto": ["vino"],
  "essencia-do-vinho-lisboa": ["vino"],
  "encontro-vinhos-sabores-lisboa": ["vino"],
  "vinhos-de-portugal-lisboa": ["vino"],
  "vinipax-beja": ["vino"],
  "barcelona-wine-week": ["vino"],
  "salon-vinos-aragon-zaragoza": ["vino"],
  "wine-paris": ["vino"],
  "prowein-dusseldorf": ["vino"],
  "its-european-congress": ["movilidad","smart-city","congreso-profesional"],
  "congreso-its-espana": ["movilidad","congreso-profesional"],
  "trafic-madrid": ["movilidad"],
  "global-mobility-call-madrid": ["movilidad","smart-city","congreso-profesional"],
  "mubil-mobility-expo-irun": ["movilidad","energia"],
  "unire-irun": ["metal-subcontratacion","maquinaria-industrial"],
  "bioterra-irun": ["ecologico","alimentacion","construccion"],
  "caravantur-irun": ["turismo","movilidad"],
  "uhinak-irun": ["ecologico","pesca-mar"],
  "go-mobility-irun": ["movilidad"],
  "rioja-wine-trade-mission-logrono": ["vino"],
  "planeta-rioja-logrono": ["vino"],
  "feria-formacion-profesional-la-rioja-logrono": ["congreso-profesional","multisectorial"],
  "feria-vehiculo-ocasion-logrono": ["automocion"],
  "feria-maquinaria-agricola-alfaro": ["agricultura-maquinaria"],
  "ferias-agroalimentarias-rioja-oriental-calahorra": ["alimentacion"],
  "navartur-pamplona": ["turismo"],
  "salon-estudiante-futuro-profesional-pamplona": ["congreso-profesional","multisectorial"],
  "edifica-pamplona": ["construccion"],
  "navarra-jobs-pamplona": ["congreso-profesional"],
  "feria-navarra-ecologica-pamplona": ["ecologico","alimentacion"],
  "navarra-wine-gastronomy-pamplona": ["vino","gastronomia-hosteleria"],
  "feria-turismo-reyno-navarra-pamplona": ["turismo"],
  "ardoaraba-vitoria": ["vino","gastronomia-hosteleria"],
  "avanza-fp-alava-vitoria": ["congreso-profesional","multisectorial"],
  "empleo-gune-vitoria": ["congreso-profesional"],
  "feria-stocks-vitoria": ["moda-textil","regalo-decoracion"],
  "lanberri-vitoria": ["cultura-arte"],
  "espacio-ribera-aranda": ["vino"],
  "premios-envero-enverofest-aranda": ["vino","gastronomia-hosteleria"],
  "congreso-la-cierna-aranda": ["vino","congreso-profesional"],
  "douro-porto-wine-festival-regua": ["vino","gastronomia-hosteleria"],
  "feira-vinhos-sabores-altos-regua": ["vino","gastronomia-hosteleria"],
  "festa-saberes-sabores-douro-regua": ["vino","gastronomia-hosteleria"],
  "sieb-valladolid": ["equipamiento-vino"],
  "enotecnica-olitecnica-oporto": ["vino","equipamiento-vino"],
  "enoforum-zaragoza": ["vino","equipamiento-vino"],
  "ficor-san-vicente-alcantara": ["equipamiento-vino","packaging"],
  "horeca-baleares-mallorca": ["gastronomia-hosteleria"],
  "fira-vi-pollenca-mallorca": ["vino"],
  "wine-days-binissalem-mallorca": ["vino","gastronomia-hosteleria"],
  "fira-sipia-alcudia-mallorca": ["gastronomia-hosteleria","pesca-mar"],
  "horeca-baleares-ibiza": ["gastronomia-hosteleria"],
  "fira-mar-ibiza": ["naval","pesca-mar"],
  "feria-stocks-ibiza": ["moda-textil","regalo-decoracion"],
  "horeca-baleares-menorca": ["gastronomia-hosteleria"],
  "fira-camp-alaior-menorca": ["ganaderia","alimentacion"],
  "arrels-menorca": ["alimentacion","gastronomia-hosteleria"],
  "bet-on-ceuta": ["digital-software","smart-city"],
  "ceuta-impulsa": ["multisectorial","congreso-profesional"],
  "odissea-economia-azul-ceuta": ["pesca-mar","multisectorial"],
  "feria-oportunidades-economicas-melilla": ["multisectorial","congreso-profesional"],
  "feria-representacion-intercultural-melilla": ["cultura-arte","multisectorial"],
  "eventos-empresariales-proyecto-melilla": ["congreso-profesional","multisectorial"],
  "maroc-in-mode-mim-tanger": ["moda-textil"],
  "tanger-nexus": ["multisectorial","congreso-profesional"],
  "tanger-fashion-week": ["moda-textil","joyeria"],
  "amith-nord-tanger": ["moda-textil"],
  "eventos-industriales-tanger-med": ["logistica","maquinaria-industrial"],
  "fira-andorra-la-vella": ["multisectorial","turismo"],
  "enfirat-encamp": ["multisectorial","automocion"],
  "andorra-taste": ["gastronomia-hosteleria","congreso-profesional"],
  "fira-del-vermut-andorra": ["vino","gastronomia-hosteleria"],
  "fira-del-bestiar-ordino": ["ganaderia","alimentacion"],
  "mercat-de-la-vall-andorra": ["regalo-decoracion","alimentacion"],
  "fira-outlet-soldeu": ["moda-textil","regalo-decoracion"],
  "motortec-madrid": ["automocion","maquinaria-industrial"],
  "feria-jamon-teruel": ["alimentacion","gastronomia-hosteleria"],
  "expocalamocha": ["ganaderia","agricultura-maquinaria"],
  "agroalcaniz": ["agricultura-maquinaria","maquinaria-industrial"],
  "foire-internationale-marseille": ["multisectorial"],
  "euromaritime-marseille": ["naval", "logistica"],
  "sirha-mediterranee-marseille": ["gastronomia-hosteleria", "alimentacion"],
  "beauty-profs-marseille": ["belleza-peluqueria", "estetica"],
  "savim-marseille": ["vino", "gastronomia-hosteleria"],
  "salon-piscine-jardin-marseille": ["construccion"],
  "solutions-cse-marseille": ["congreso-profesional", "multisectorial"],
  "japan-expo-sud-marseille": ["pop-videojuegos"],
  "herofestival-marseille": ["pop-videojuegos"],
  "siac-marseille": ["cultura-arte"],
  "cannes-yachting-festival": ["naval","turismo"],
  "mapic-cannes": ["congreso-profesional","regalo-decoracion"],
  "medagri-avignon": ["agricultura-maquinaria","ganaderia"],
  "foire-internationale-toulouse": ["multisectorial"],
  "cfia-toulouse": ["alimentacion", "packaging", "maquinaria-industrial"],
  "sepem-industries-toulouse": ["maquinaria-industrial", "metal-subcontratacion"],
  "aerospace-test-development-show-toulouse": ["aeronautica"],
  "aeromart-toulouse": ["aeronautica", "congreso-profesional"],
  "siane-toulouse": ["maquinaria-industrial", "metal-subcontratacion"],
  "foire-exposition-perpignan": ["multisectorial"]
};

// Helpers
export const activitiesForFair = (slug) => fairActivities[slug] || [];
export const colorForTag = (tag) => (tagFamilies[fairTags[tag]?.family]?.color) || '#6F757D';
export const labelForTag = (tag, lang) => (fairTags[tag]?.label?.[lang]) || fairTags[tag]?.label?.es || tag;
export const familyLabel = (fam, lang) => (tagFamilies[fam]?.label?.[lang]) || tagFamilies[fam]?.sector || fam;

// Lista de etiquetas en orden de familia (para el índice y los chips agrupados).
export const tagOrder = Object.keys(fairTags).sort((a, b) => {
  const fa = Object.keys(tagFamilies).indexOf(fairTags[a].family);
  const fb = Object.keys(tagFamilies).indexOf(fairTags[b].family);
  return fa - fb;
});

// Índice inverso: etiqueta -> [slugs de feria]. Se construye una vez al cargar el módulo.
const _fairsByTag = (() => {
  const idx = {};
  for (const tag of Object.keys(fairTags)) idx[tag] = [];
  for (const [slug, tags] of Object.entries(fairActivities)) {
    for (const t of tags) (idx[t] || (idx[t] = [])).push(slug);
  }
  return idx;
})();
export const fairsForActivity = (tag) => _fairsByTag[tag] || [];
export const fairCountForActivity = (tag) => (_fairsByTag[tag] || []).length;
