// Renders 3D de proyectos para la Galería y el carrusel de las paralelas.
// Ficheros en static/img/galeria-renders/ (1600 px y variante -800).
// Leyendas descriptivas, sin nombre del cliente.
export const RENDERS_DIR = '/img/galeria-renders/';
export const galleryRenders = [
  { f: 'stand-bodega-barra-degustacion-vista-cenital', w: 1600, h: 1200, cap: { es: 'Stand de bodega en madera clara: barra de degustación, botellero iluminado, almacén cerrado y zona de reuniones', en: 'Winery stand in light wood: tasting bar, lit bottle display, closed storage and meeting area', pt: 'Stand de adega em madeira clara: balcão de degustação, garrafeira iluminada, arrumo fechado e zona de reuniões', de: 'Weingut-Messestand in hellem Holz: Verkostungstheke, beleuchtetes Flaschenregal, Lager und Besprechungsbereich', fr: 'Stand de domaine viticole en bois clair : bar de dégustation, présentoir à bouteilles éclairé, réserve et espace de réunion', it: 'Stand di cantina in legno chiaro: banco degustazione, espositore bottiglie illuminato, magazzino e area riunioni', nl: 'Wijnhuisstand in licht hout: proefbar, verlichte flessenwand, berging en vergaderhoek' } },
  { f: 'stand-bodega-botellero-iluminado', w: 1600, h: 983, cap: { es: 'Stand de bodega: gráfica de viñedo a gran formato, botellero retroiluminado y barra con taburetes', en: 'Winery stand: large-format vineyard graphics, backlit bottle display and bar with stools', pt: 'Stand de adega: gráfica de vinha em grande formato, garrafeira retroiluminada e balcão com bancos', de: 'Weingut-Stand: großformatige Weinberggrafik, hinterleuchtetes Flaschenregal und Theke mit Hockern', fr: 'Stand viticole : visuel de vignoble grand format, présentoir rétroéclairé et bar avec tabourets', it: 'Stand di cantina: grafica di vigneto in grande formato, espositore retroilluminato e banco con sgabelli', nl: 'Wijnhuisstand: grootformaat wijngaardbeeld, verlichte flessenwand en bar met krukken' } },
  { f: 'stand-gourmet-doble-altura-lamas-madera', w: 1600, h: 772, cap: { es: 'Stand gourmet con cuerpo elevado de lamas de madera, barra central y mesas altas de degustación', en: 'Gourmet food stand with a raised wooden-slat volume, central bar and high tasting tables', pt: 'Stand gourmet com volume elevado de ripas de madeira, balcão central e mesas altas de degustação', de: 'Gourmet-Messestand mit erhöhtem Lamellenkörper aus Holz, zentraler Theke und Stehtischen', fr: 'Stand gastronomique avec volume suspendu à lames de bois, bar central et tables hautes de dégustation', it: 'Stand gourmet con volume sospeso a lamelle di legno, banco centrale e tavoli alti da degustazione', nl: 'Gourmetstand met verhoogd volume van houten lamellen, centrale bar en statafels' } },
  { f: 'stand-gourmet-zona-degustacion-barra', w: 1600, h: 786, cap: { es: 'Zona de degustación de un stand gourmet: barra de madera, mesas altas y área de mesas con butacas', en: 'Tasting area of a gourmet stand: wooden bar, high tables and seated dining area', pt: 'Zona de degustação de um stand gourmet: balcão de madeira, mesas altas e área de mesas com cadeirões', de: 'Verkostungsbereich eines Gourmet-Stands: Holztheke, Stehtische und Sitzbereich', fr: 'Espace de dégustation d’un stand gastronomique : bar en bois, tables hautes et coin repas', it: 'Area degustazione di uno stand gourmet: banco in legno, tavoli alti e zona con poltroncine', nl: 'Proefruimte van een gourmetstand: houten bar, statafels en zithoek' } },
  { f: 'stand-gourmet-interior-desde-pasillo', w: 1600, h: 786, cap: { es: 'El mismo stand gourmet visto desde el pasillo: banco corrido, lamas y cerramientos traslúcidos', en: 'The same gourmet stand seen from the aisle: built-in bench, slats and translucent walls', pt: 'O mesmo stand gourmet visto do corredor: banco corrido, ripas e divisórias translúcidas', de: 'Derselbe Gourmet-Stand vom Gang aus: Sitzbank, Lamellen und transluzente Wände', fr: 'Le même stand vu depuis l’allée : banquette, lames et cloisons translucides', it: 'Lo stesso stand visto dal corridoio: panca continua, lamelle e pareti traslucide', nl: 'Dezelfde stand vanaf het gangpad: doorlopende bank, lamellen en doorschijnende wanden' } }
,
  { f: 'stand-vinos-dos-marcas-madera-y-negro', w: 1600, h: 783, cap: { es: 'Stand compartido de vinos para dos marcas: módulo en madera clara con barra y módulo negro con botelleros retroiluminados', en: 'Shared wine stand for two brands: light-wood module with bar and black module with backlit bottle displays', pt: 'Stand de vinhos partilhado por duas marcas: módulo em madeira clara com balcão e módulo preto com garrafeiras retroiluminadas', de: 'Gemeinsamer Weinstand für zwei Marken: Modul in hellem Holz mit Theke und schwarzes Modul mit hinterleuchteten Flaschenregalen', fr: 'Stand de vins partagé par deux marques : module en bois clair avec bar et module noir avec présentoirs rétroéclairés', it: 'Stand di vini condiviso da due marchi: modulo in legno chiaro con banco e modulo nero con espositori retroilluminati', nl: 'Gedeelde wijnstand voor twee merken: module in licht hout met bar en zwarte module met verlichte flessenwanden' } },
  { f: 'stand-industrial-volumen-facetado-azul', w: 1600, h: 946, cap: { es: 'Stand industrial con gran volumen facetado en blanco y azul, zona de reuniones y mostrador de recepción', en: 'Industrial stand with a large faceted white-and-blue volume, meeting area and reception counter', pt: 'Stand industrial com grande volume facetado em branco e azul, zona de reuniões e balcão de receção', de: 'Industriestand mit großem facettiertem Volumen in Weiß und Blau, Besprechungsbereich und Empfangstheke', fr: 'Stand industriel avec grand volume facetté blanc et bleu, espace de réunion et comptoir d’accueil', it: 'Stand industriale con grande volume sfaccettato bianco e blu, area riunioni e banco reception', nl: 'Industriële stand met groot gefacetteerd volume in wit en blauw, vergaderhoek en ontvangstbalie' } },
  { f: 'stand-energia-doble-altura-acristalado', w: 1600, h: 586, fit: 'contain', cap: { es: 'Stand de gran formato para una energética: cuerpo superior retroiluminado, frente acristalado, zonas lounge y gráfica de vegetación', en: 'Large-format energy company stand: backlit upper volume, glazed front, lounge areas and nature graphics', pt: 'Stand de grande formato para uma energética: volume superior retroiluminado, frente envidraçada, zonas lounge e gráfica de vegetação', de: 'Großformatiger Stand eines Energieversorgers: hinterleuchteter Oberbau, verglaste Front, Lounges und Naturgrafik', fr: 'Stand grand format pour un énergéticien : volume supérieur rétroéclairé, façade vitrée, espaces lounge et visuels végétaux', it: 'Stand di grande formato per un’azienda energetica: volume superiore retroilluminato, fronte vetrato, aree lounge e grafica vegetale', nl: 'Grootformaat stand voor een energiebedrijf: verlicht bovenvolume, glazen gevel, lounges en natuurbeelden' } },
  { f: 'mobiliario-vino-expositor-desmontable', w: 1600, h: 791, cap: { es: 'Mobiliario a medida para una bodega: barra y expositor desmontables por encaje, con botellero, copero y caja de luz', en: 'Custom furniture for a winery: slot-together bar and display unit with bottle rack, glass rack and lightbox', pt: 'Mobiliário à medida para uma adega: balcão e expositor desmontáveis por encaixe, com garrafeira, porta-copos e caixa de luz', de: 'Maßmöbel für ein Weingut: steckbare Theke und Vitrine mit Flaschenregal, Glashalter und Leuchtkasten', fr: 'Mobilier sur mesure pour un domaine : bar et présentoir démontables par emboîtement, avec casier, porte-verres et caisson lumineux', it: 'Arredo su misura per una cantina: banco ed espositore smontabili a incastro, con portabottiglie, portabicchieri e cassonetto luminoso', nl: 'Maatmeubilair voor een wijnhuis: in elkaar schuivende bar en vitrine met flessenrek, glazenrek en lichtbak' } }
];

export const renderCaption = (r, lang) => r.cap[lang] || r.cap.en;
