// Slugs nativos en japonés (solo idioma `ja`).
//
// El resto de idiomas comparten el slug latino de cada feria/proyecto (definido en
// fairsData/projectData). Para `ja` queremos URLs en japonés nativo, así que aquí
// mapeamos slug-latino -> slug-japonés. Lo que no esté mapeado cae al slug latino.
//
// - Segmento de detalle de feria en ja: 展示会情報 (igual que la landing). El resto de
//   idiomas mantienen su segmento de detalle actual `ferias` (ya indexado).

/** slug latino de feria -> slug japonés */
export const jaFairSlugs = {
  "agroexpo-feval-don-benito": "アグロエクスポフェバル-ドンベニート",
  "feria-de-fp-badajoz": "fp職業訓練フェア-バダホス",
  "feria-de-los-mayores-de-extremadura-badajoz": "高齢者フェア-バダホス",
  "fio-monfrague": "fio-ヨーロッパ",
  "feria-de-belleza-moda-y-cosmetica-badajoz": "美容ファッション化粧品フェア-バダホス",
  "vinac-almendralejo": "ビナック-アルメンドラレホ",
  "artexania-plasencia": "工芸フェア-プラセンシア",
  "fenavin-match-ciudad-real": "フェナビンマッチ-シウダーレアル",
  "ferduque-ciudad-real": "フェルドゥケ-シウダーレアル",
  "jec-world-paris": "jecワールド-パリ",
  "logimat-stuttgart": "ロジマット-シュトゥットガルト",
  "global-industrie-paris": "グローバルインダストリー-パリ",
  "ecuextre-badajoz": "エクエクストレ-バダホス",
  "hannover-messe": "ハノーバーメッセ-ヨーロッパ",
  "sagalexpo-lisboa": "サガルエキスポ-リスボン",
  "sil-lisboa": "sil-リスボン",
  "fercam-manzanares-ciudad-real": "フェルカムマンサナレス-シウダーレアル",
  "portugal-smart-cities-summit": "ポルトガルスマートシティサミット-ポルト",
  "arcolisboa": "アルコ-リスボン",
  "des-malaga": "des-マラガ",
  "cm-malaga": "cm-マラガ",
  "foro-greencities-malaga": "グリーンシティーズフォーラム-マラガ",
  "fercatur-ciudad-real": "フェルカトゥール-シウダーレアル",
  "feciex-badajoz": "フェシエクス-バダホス",
  "san-diego-comic-con-malaga": "サンディエゴコミコン-マラガ",
  "expo-agritech-malaga": "アグリテックエキスポ-マラガ",
  "simed-malaga": "シメッド-マラガ",
  "fehispor-badajoz": "フェイスポル-バダホス",
  "amb-stuttgart": "amb-シュトゥットガルト",
  "iberocio-badajoz": "イベロシオ-バダホス",
  "sps-nuremberg": "sps-ニュルンベルク",
  "automatica-munich": "オートマティカ-ミュンヘン",
  "pollutec-lyon": "ポリュテック-リヨン",
  "bauma-munich": "バウマ-ミュンヘン",
  "fireca-sevilla": "フィレカ-セビリア",
  "conxemar-vigo": "コンセマール-ビーゴ",
  "veteco-madrid": "ベテコ-マドリード",
  "piscimad-madrid": "ピスシマド-マドリード",
  "greencities-malaga": "グリーンシティーズ-マラガ",
  "iberpet-madrid": "イベルペット-マドリード",
  "ht-malaga": "ht-マラガ",
  "eurosatory-paris": "ユーロサトリ-パリ",
  "empack-madrid": "エンパック-マドリード",
  "expoquimia-barcelona": "エクスポキミア-バルセロナ",
  "mwc-barcelona": "mwc-バルセロナ",
  "ise-barcelona": "ise-バルセロナ",
  "alimentaria-barcelona": "アリメンタリア-バルセロナ",
  "hispack-barcelona": "イスパック-バルセロナ",
  "hostelco-barcelona": "オステルコ-バルセロナ",
  "smart-city-expo-world-congress-barcelona": "スマートシティエキスポ世界会議-バルセロナ",
  "construmat-barcelona": "コンストルマット-バルセロナ",
  "iot-solutions-world-congress-barcelona": "iotソリューションズ世界会議-バルセロナ",
  "smart-doors-madrid": "スマートドアーズ-マドリード",
  "equiplast-barcelona": "エキプラスト-バルセロナ",
  "tis-sevilla": "tis-セビリア",
  "autentica-sevilla": "アウテンティカ-セビリア",
  "esicm-lives-lisboa": "esicmライブス-リスボン",
  "lisbon-food-affair": "リスボンフードフェア-リスボン",
  "snackex-lisboa": "スナックエクス-リスボン",
  "gse-expo-lisboa": "gseエキスポ-リスボン",
  "esra-congress-lisboa": "esra会議-リスボン",
  "world-aviation-festival-lisboa": "世界航空フェスティバル-リスボン",
  "pegs-europe-lisboa": "ペグスヨーロッパ-リスボン",
  "btl-lisboa": "btl-リスボン",
  "smopyc-zaragoza": "スモピック-サラゴサ",
  "fima-zaragoza": "フィマ-サラゴサ",
  "feria-internacional-ganadera-zafra": "国際畜産フェア-サフラ",
  "web-summit-lisboa": "ウェブサミット-リスボン",
  "tektonica-lisboa": "テクトニカ-リスボン",
  "biemh-bilbao": "biemh-ビルバオ",
  "subcontratacion-bilbao": "下請けフェア-ビルバオ",
  "addit3d-bilbao": "アディット3d-ビルバオ",
  "bedigital-bilbao": "ビーデジタル-ビルバオ",
  "pumps-valves-bilbao": "ポンプバルブ-ビルバオ",
  "maintenance-bilbao": "メンテナンスフェア-ビルバオ",
  "fruit-attraction-madrid": "フルーツアトラクション-マドリード",
  "salon-look-madrid": "サロンルック-マドリード",
  "madrid-tech-show": "テックショー-マドリード",
  "the-district-madrid": "ザディストリクト-マドリード",
  "intergift-madrid": "インターギフト-マドリード",
  "momad-madrid": "モマド-マドリード",
  "madridjoya-madrid": "マドリードホヤ-マドリード",
  "bisutex-madrid": "ビスーテックス-マドリード",
  "fitur-madrid": "フィトゥール-マドリード",
  "arcomadrid": "アルコ-マドリード",
  "salon-gourmets-madrid": "サロングルメ-マドリード",
  "rebuild-madrid": "リビルド-マドリード",
  "madrid-fusion": "マドリードフュージョン-マドリード",
  "expofranquicia-madrid": "エクスポフランチャイズ-マドリード",
  "concreta-oporto": "コンクレタ-ポルト",
  "expocosmetica-oporto": "エクスポコスメティカ-ポルト",
  "empack-oporto": "エンパック-ポルト",
  "itf-intertex-oporto": "itfインターテックス-ポルト",
  "expomecanica-oporto": "エキスポメカニカ-ポルト",
  "emaf-oporto": "エマフ-ポルト",
  "portojoia-oporto": "ポルトジョイア-ポルト",
  "decor-hotel-oporto": "デコールホテル-ポルト",
  "expocarne-oporto": "エキスポカルネ-ポルト",
  "cevisama-valencia": "セビサマ-バレンシア",
  "habitat-valencia": "アビタット-バレンシア",
  "textilhogar-valencia": "テキスティルオガール-バレンシア",
  "espacio-cocina-sici-valencia": "キッチンスペースsici-バレンシア",
  "fimma-maderalia-valencia": "フィママ-マデラリア-バレンシア",
  "iberflora-valencia": "イベルフローラ-バレンシア",
  "gastronoma-valencia": "ガストロノマ-バレンシア",
  "eurobrico-valencia": "エウロブリコ-バレンシア",
  "palma-international-boat-show": "パルマインターナショナルボートショー-マヨルカ",
  "palma-superyacht-village": "パルマスーパーヨットビレッジ-マヨルカ",
  "baleart-mallorca": "バレアート-マヨルカ",
  "dijous-bo-mallorca": "ディジョウスボ-マヨルカ",
  "figan-zaragoza": "フィガン-サラゴサ",
  "enomaq-zaragoza": "エノマック-サラゴサ",
  "oleomaq-zaragoza": "オレオマック-サラゴサ",
  "tecnovid-zaragoza": "テクノビッド-サラゴサ",
  "navalia-vigo": "ナバリア-ビーゴ",
  "nortrans-vigo": "ノルトランス-ビーゴ",
  "moldplas-batalha": "モルドプラス-バターリャ",
  "expometal-batalha": "エキスポメタル-バターリャ",
  "stone-iberica-batalha": "ストーンイベリカ-バターリャ",
  "vidrotec-batalha": "ビドロテック-バターリャ",
  "decorhotel-batalha": "デコールホテル-バターリャ",
};

/** id de proyecto (latino) -> slug japonés */
export const jaProjectSlugs = {
  // (fase de proyectos)
};

/** Inversa: slug japonés -> slug latino (para resolver la URL entrante). */
export const jaFairSlugsReverse = Object.fromEntries(
  Object.entries(jaFairSlugs).map(([es, ja]) => [ja, es])
);
export const jaProjectSlugsReverse = Object.fromEntries(
  Object.entries(jaProjectSlugs).map(([es, ja]) => [ja, es])
);
