<?php

return array(
    'site_url' => 'https://standarte.es',
    'from_email' => 'promo@standarte.es',
    'from_name' => 'Standarte',
    'reply_to' => 'promo@standarte.es',
    'envelope_sender' => 'promo@standarte.es',
    'smtp' => array(
        'enabled' => true,
        'host' => 'ssl0.ovh.net',
        'port' => 587,
        'encryption' => 'tls',
        'username' => 'promo@standarte.es',
        'password' => getenv('STANDARTE_SMTP_PASSWORD') ? getenv('STANDARTE_SMTP_PASSWORD') : 'Extrategia37',
        'timeout' => 20
    ),
    'phone' => '+34 613 097 148',
    'login_password_hash' => '$2y$10$mzzI3Iz2LFkNoYgXrqRvO.iUzdJAO1Qy8qfBPY/QRk3BPqKKRN8mG',
    'languages' => array(
        'es' => array('label' => 'Español', 'html' => 'es'),
        'en' => array('label' => 'English', 'html' => 'en'),
        'de' => array('label' => 'Deutsch', 'html' => 'de'),
        'pt' => array('label' => 'Português', 'html' => 'pt'),
        'zh' => array('label' => '中文', 'html' => 'zh'),
        'hi' => array('label' => 'हिन्दी', 'html' => 'hi')
    ),
    'header_text' => array(
        'es' => 'Diseño y Construcción de Stands Internacionales',
        'en' => 'International Exhibition Stand Design & Construction',
        'de' => 'Internationales Messedesign & Standbau',
        'pt' => 'Design e Construção de Stands Internacionais',
        'zh' => '国际展位设计与搭建',
        'hi' => 'अंतर्राष्ट्रीय प्रदर्शनी स्टैंड डिजाइन और निर्माण'
    ),
    'footer_text' => array(
        'es' => 'Si desea más información, responda a este correo o contacte en',
        'en' => 'For more information, please reply to this email or contact us at',
        'de' => 'Für weitere Informationen antworten Sie bitte auf diese E-Mail o. kontaktieren Sie uns unter',
        'pt' => 'Se desejar mais informações, responda a este email o. contacte pelo',
        'zh' => '如需更多信息，请回复此邮件或联系我们：',
        'hi' => 'अधिक जानकारी के लिए, कृपया इस ईमेल का उत्तर दें या संपर्क करें'
    ),
    'categories' => array(
        'stands_madera' => array(
            'label' => 'Stands de Madera',
            'subject' => '¿Está {EMPRESA} preparada para liderar su próxima feria o pasará desapercibida?',
            'preheader' => 'Soluciones exclusivas de diseño y acabados artesanales de alta calidad.',
            'headline' => 'Con nosotros de su lado {EMPRESA} se convertirá en el centro de todas las miradas',
            'intro' => 'En un pabellón saturado de ruido visual, la mayoría de los stands pasan desapercibidos. En Standarte, diseñamos y fabricamos stands basados en la psicología de la atención dirigidos a proyectar una imagen diferenciadora y equilibrada.',
            'body' => 'Nuestros carpinteros especializados logran acabados perfectos. Nos encargamos de toda la ingeniería, fabricación y montaje para que el proyecto de {EMPRESA} sea el centro de todas las miradas.',
            'cta' => 'DISEÑAR MI STAND',
            'translations' => array(
                'en' => array(
                    'subject' => 'Is {EMPRESA} ready to dominate the show, or will you blend in?',
                    'preheader' => 'Exclusive bespoke solutions and premium handcrafted finishes.',
                    'headline' => '{EMPRESA}: Lead your market and become the absolute center of attention',
                    'intro' => 'Let\'s be honest: in an exhibition hall filled with visual noise, most stands are completely ignored. For {EMPRESA}, we design and build bespoke stands that project maximum quality, brand authority, and visual balance.',
                    'body' => 'Our specialized master craftsmen deliver flawless finishes. We handle the entire engineering, manufacturing, and setup process, making {EMPRESA} the absolute center of attention.',
                    'cta' => 'DESIGN MY STAND'
                ),
                'de' => array(
                    'subject' => 'Ist {EMPRESA} bereit, die Messe zu dominieren, oder gehen Sie unter?',
                    'preheader' => 'Exklusive maßgeschneiderte Lösungen und handgefertigte Oberflächen.',
                    'headline' => '{EMPRESA}: Führen Sie Ihren Markt an und stehen Sie im Rampenlicht',
                    'intro' => 'Seien wir ehrlich: In einer Messehalle voller visuellem Lärm gehen die meisten Stände unter. Für {EMPRESA} entwerfen und fertigen wir exklusive Messestände, die Qualität, Stärke und optische Balance ausstrahlen.',
                    'body' => 'Unsere spezialisierten Handwerker erzielen makellose Ergebnisse. Wir übernehmen den gesamten Engineering-, Fertigungs- und Montageprozess für {EMPRESA}.',
                    'cta' => 'MESSESTAND ENTWERFEN'
                ),
                'pt' => array(
                    'subject' => 'Está a {EMPRESA} pronta para liderar a sua próxima feira ou passará despercebida?',
                    'preheader' => 'Soluções exclusivas e acabamentos artesanais de alta qualidade.',
                    'headline' => '{EMPRESA}: Lidere o seu setor e torne-se o centro de todas as atenções',
                    'intro' => 'Sejamos realistas: num pavilhão cheio de ruído visual, a maioria dos stands passa despercebida. Para {EMPRESA}, projetamos e fabricamos stands sob medida que transmitem máxima qualidade e solidez diferenciada.',
                    'body' => 'Nossos carpinteiros especializados garantem acabamentos impecáveis. Cuidamos de todo o processo de engenharia, fabricação e montagem para que {EMPRESA} sea o centro de todas as atenções.',
                    'cta' => 'PROJETAR O MEU STAND'
                ),
                'zh' => array(
                    'subject' => '{EMPRESA} 准备好在下一届展会上脱颖而出，还是会默默无闻？',
                    'preheader' => '独家定制设计方案与高品质手工打造。',
                    'headline' => '有了我们的支持，{EMPRESA} 将成为全场瞩目的焦点',
                    'intro' => '在充满视觉噪音的展馆中，大多数展位都会被忽视。在 Standarte，我们基于注意力心理学设计和建造展位，旨在呈现出与众不同且平衡的品牌形象。',
                    'body' => '我们专业的木匠能打造出完美的工艺细节。我们负责从工程设计、制造到搭建的全过程，让 {EMPRESA} 的项目成为绝对的焦点。',
                    'cta' => '设计我的展位'
                ),
                'hi' => array(
                    'subject' => 'क्या {EMPRESA} अपने अगले ट्रेड शो का नेतृत्व करने के लिए तैयार है, या अनदेखी रह जाएगी?',
                    'preheader' => 'विशेष कस्टम डिज़ाइन समाधान और उच्च गुणवत्ता वाली शिल्पकारी।',
                    'headline' => 'हमारे साथ, {EMPRESA} हर किसी के आकर्षण का केंद्र बन जाएगी',
                    'intro' => 'दृश्य शोर से भरे प्रदर्शनी हॉल में, अधिकांश स्टैंड अनदेखे रह जाते हैं। Standarte में, हम ध्यान के मनोविज्ञान पर आधारित स्टैंड डिज़ाइन और निर्मित करते हैं, जिसका उद्देश्य एक अलग और संतुलित छवि पेश करना है।',
                    'body' => 'हमारे विशेषज्ञ बढ़ई त्रुटिहीन फिनिश प्रदान करते हैं। हम संपूर्ण इंजीनियरिंग, निर्माण और सेटअप प्रक्रिया का प्रबंधन करते हैं, जिससे {EMPRESA} का प्रोजेक्ट आकर्षण का केंद्र बन जाता है।',
                    'cta' => 'मेरा स्टैंड डिज़ाइन करें'
                )
            ),
            'images' => array(
                array('src' => 'img/trabajos/01/02.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/01/FD.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/01/FD2.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/01/FH.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/01/FH2.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/01/hine copia.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/01/hine.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/01/land1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/01/land2.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/01/land2B.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/01/land3.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/01/land4.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/01/land4B.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/01/land5.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/01/land6.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/01/land6B.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/01/land7.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/01/land8.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/01/land8B.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/01/portada.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/01/rive.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCANTICO/1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCANTICO/1.webp', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCANTICO/2.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCANTICO/2.webp', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCBUCHHEISTER/1.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCCONSTELLIUM/1.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCCONSTELLIUM/1.webp', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCCONSTELLIUM/2.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCCONSTELLIUM/2.webp', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCCONSTELLIUM/3.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCCONSTELLIUM/4.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCCONSTELLIUM/5.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCCONSTELLIUM/6.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCDENTSUAEGIS/1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCDENTSUAEGIS/2.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCDENTSUAEGIS/3.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCDENTSUAEGIS/4.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCDENTSUAEGIS/5.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCELUMATEC/2.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCELUMATEC/2.webp', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCELUMATEC/3.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCELUMATEC/4.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCELUMATEC/4.webp', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCEMIL/1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCEMIL/1.webp', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCETXE-TAR/1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCFAGORARRASATE/1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCFARNEL/1.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCFARNEL/1.webp', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCFARNEL/2.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCFARNEL/2.webp', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCFARNEL/3.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCFARNEL/4.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCFARNEL/5.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCFARNEL/6.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCFARNEL/7.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCMAGNOLIA/1.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCMAGNOLIA/1.png', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCMAGNOLIA/1.webp', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCMAGNOLIA/2.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCMAGNOLIA/2.png', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCMAGNOLIA/2.webp', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCMAGNOLIA/3.png', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCMAGNOLIA/4.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCMAGNOLIA/4.png', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCMAGNOLIA/5.png', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCMFI/1.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCMFI/1.webp', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCMFI/2.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCMFI/2.webp', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCMFI/3.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCMFI/4.png', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCMFI/5.png', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCMFI/6.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCMFI/7.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCMFI/8jpg.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCORGADATA/1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCORGADATA/1.webp', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCORGADATA/2.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCORGADATA/2.webp', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCORGADATA/3.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCORGADATA/4.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCPHARMA/1.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCPHARMA/1.webp', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCPHARMA/2.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCPHARMA/2.webp', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCPHARMA/meplan_designstand_messebau-1-1397x700.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCPHARMA/meplan_designstand_messebau_pharmatechnik-.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCPHARMA/meplan_pharmatechnik_standbau.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCPHARMA/messestandbau_meplan_designstand-1397x700.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCPHARMA/pharmatechnik_designstand_meplan-1397x700.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCREMIS/1.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCREMIS/2.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCREMIS/3.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/1.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/2.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/2.webp', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/3.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/4.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/4.webp', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/5.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/6.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCSCHOEFFEL/7.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TCSES/1.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCSES/1.webp', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/TCSES/2.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCSES/2.webp', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TCSES/3.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TCWURTH/1.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/TCWURTH/2.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/TELASRGB/1.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TELASRGB/1.webp', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TELASRGB/2.webp', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TELASRGB/2010-04_Philips_Light Building_073.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TELASRGB/keynote_2010-04_fair_markenarchitektur_philips_light&building_4.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/TELASRGB/keynote_2010-04_fair_markenarchitektur_philips_light&building_5.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/TELASRGB/keynote_2010-04_fair_markenarchitektur_philips_light&building_6.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/TELASRGB/keynote_2010-04_mediatecture_markenarchitektur_philips_light&building_2.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/01-bost-emo-2023_1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/01-stand-tecnalia-biemh-2022_1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/01-stand-zayer-biemh-2022-v2.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/02-bost-emo-2023_1.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/trabajos_promueve/02-stand-intermaher-biemh-2022.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/trabajos_promueve/02-stand-zayer-biemh-2022.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/trabajos_promueve/03-stand-intermaher-biemh-2022.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/trabajos_promueve/03-stand-tecnalia-biemh-2022_1.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/04-bost-emo-2023_2.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/06-stand-zayer-biemh-2022.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/trabajos_promueve/1.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/trabajos_promueve/2 copia.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/2.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/3.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/trabajos_promueve/bauma-ulma-2013-2.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/bellota-ferroforma.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/biemh-16-tecnalia-1.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/trabajos_promueve/cabecera-proyecto-emo-milano-2021-2.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/trabajos_promueve/evento-2014-fanuc-showroom-1.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/trabajos_promueve/evento-2014-fanuc-showroom-2.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/trabajos_promueve/keynote_2010-04_fair_markenarchitektur_philips_light&building_5.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/trabajos_promueve/mg-1225.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/stand-2016-biemh-emuge-4.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/trabajos_promueve/stand-2018-biemh-delteco-10.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/stand-cun-fitur3.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/stand-emuge-biemh-2022.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/stands-2014-biemh-bilbao-zayer-17.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/stands-2014-biemh-bilbao-zayer-20.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/stands-pescanova.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/trabajos_promueve/STANDS_2017_EMO_HANNOVER_ZAYER_1.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/01-bost-emo-2023_1.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/01-stand-tecnalia-biemh-2022_1.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/01-stand-zayer-biemh-2022-v2.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/02-bost-emo-2023_1.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/02-stand-intermaher-biemh-2022.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/02-stand-zayer-biemh-2022.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/03-stand-intermaher-biemh-2022.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/03-stand-tecnalia-biemh-2022_1.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/04-bost-emo-2023_2.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/06-stand-zayer-biemh-2022.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/2 copia.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/3.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/bellota-ferroforma.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/biemh-16-tecnalia-1.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/cabecera-proyecto-emo-milano-2021-2.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/evento-2014-fanuc-showroom-1.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/evento-2014-fanuc-showroom-2.jpg', 'alt' => 'Stand de diseño premium de madera'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/mg-1225.jpg', 'alt' => 'Stand ferial corporativo y elegante'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/stand-2016-biemh-emuge-4.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/stand-2018-biemh-delteco-10.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/stand-cun-fitur3.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/stand-emuge-biemh-2022.jpg', 'alt' => 'Stand de diseño con carpintería artesanal'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/stands-2014-biemh-bilbao-zayer-17.jpg', 'alt' => 'Stand ecológico y sostenible'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/stands-2014-biemh-bilbao-zayer-20.jpg', 'alt' => 'Arquitectura efímera para eventos'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/stands-pescanova.jpg', 'alt' => 'Fabricación y montaje de stands'),
                array('src' => 'img/trabajos/trabajos_promueve/thumbs/STANDS_2017_EMO_HANNOVER_ZAYER_1.jpg', 'alt' => 'Stand de diseño premium de madera')
            )
        )
    )
);
